### ISSUE TITLE
Delay startup of marvel plugin

### ISSUE THREAD

**Issue by markwalkom** [elasticsearch/elasticsearch#5119]
When starting up an ES node with the marvel plugin installed, before the node can connect to or start a cluster it complains every second that it cannot connect to upload stats which generates a lot of noise in the logs;
```
[2014-02-14 10:32:10,991][ERROR][marvel.agent.exporter    ] error connecting to [localhost:9200]
java.net.ConnectException: Connection refused
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:579)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
        at sun.net.www.http.HttpClient.New(HttpClient.java:308)
        at sun.net.www.http.HttpClient.New(HttpClient.java:326)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:996)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:932)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:850)
        at org.elasticsearch.marvel.agent.exporter.ESExporter.openConnection(ESExporter.java:317)
        at org.elasticsearch.marvel.agent.exporter.ESExporter.openExportingConnection(ESExporter.java:198)
        at org.elasticsearch.marvel.agent.exporter.ESExporter.exportXContent(ESExporter.java:246)
        at org.elasticsearch.marvel.agent.exporter.ESExporter.exportNodeStats(ESExporter.java:135)
        at org.elasticsearch.marvel.agent.AgentService$ExportingWorker.exportNodeStats(AgentService.java:274)
        at org.elasticsearch.marvel.agent.AgentService$ExportingWorker.run(AgentService.java:174)
        at java.lang.Thread.run(Thread.java:744)
[2014-02-14 10:32:10,991][ERROR][marvel.agent.exporter    ] could not connect to any configured elasticsearch instances: [localhost:9200]
```

It'd be nicer if marvel could wait until cluster state is established and then start stats collection.

**Comment by bleskes** [comment]
should be fixed as of marvel 1.1. With Marvel 1.3, if we a host target is not configured and we know we send locally, we wait for the local http server to start before starting to send data.
