### ISSUE TITLE
Can't start embedded ES after upgrade to 1.2.0

### ISSUE THREAD

**Issue by mkathuria** [elasticsearch/elasticsearch#6382]
Can not start embedded Elastic Search process after upgrading to 1.2.0.

Error says: 
A binding to org.elasticsearch.indices.analysis.IcuIndicesAnalysis was already configured at _unknown_.

I am starting embedded elastic search server from storm worker process. I have updated the plugins for version 1.2.0. Saw somewhere that this is due to older version of plugins in classpath but that is not the case here.

On startup, it gives me error.

https://gist.github.com/mkathuria/76a6883c16bb55b8b7fd

I logged the classpath (of the spawning process) while starting the embedded node.. This contains only storm jars in classpath.

https://gist.github.com/mkathuria/9476bb7bbd3f2a3c4101

**Comment by mkathuria** [comment]
@clintongormley  Again seeing this issue while starting embedded node.  As per your comment, I checked that ntp and syslog are up. 

 /etc/init.d/rsyslog status
rsyslogd (pid  855) is running...

ntpstat 
synchronised to NTP server (10.0.0.95) at stratum 4 
   time correct to within 86 ms
   polling server every 1024 s


Caused by: org.elasticsearch.common.inject.CreationException: Guice creation errors:

1) A binding to org.elasticsearch.indices.analysis.smartcn.SmartChineseIndicesAnalysis was already configured at _unknown_.
  at _unknown_

2) A binding to org.elasticsearch.indices.analysis.IcuIndicesAnalysis was already configured at _unknown_.
  at _unknown_

3) A binding to org.elasticsearch.indices.analysis.KuromojiIndicesAnalysis was already configured at _unknown_.
  at _unknown_

3 errors
        at org.elasticsearch.common.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:344) ~[stormjar.jar:na]
        at org.elasticsearch.common.inject.InjectorBuilder.initializeStatically(InjectorBuilder.java:151) ~[stormjar.jar:na]
        at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:102) ~[stormjar.jar:na]
        at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:93) ~[stormjar.jar:na]
        at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:70) ~[stormjar.jar:na]
        at org.elasticsearch.common.inject.ModulesBuilder.createInjector(ModulesBuilder.java:59) ~[stormjar.jar:na]
        at org.elasticsearch.node.internal.InternalNode.<init>(InternalNode.java:197) ~[stormjar.jar:na]
        at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:159) ~[stormjar.jar:na]
        at com.spr.search.repository.elasticsearch.embedded.EmbeddedESServerManagerImpl.createEmbeddedServerNode(EmbeddedESServerManagerImpl.java:102) ~[stormjar.jar:na]
