### ISSUE TITLE
Tribe node fails on index close.

### ISSUE THREAD

**Issue by zazasa** [elasticsearch/elasticsearch#6411]
Hi, 
I have 1 tribe node, on 1 cluster with 1 master and 2 data nodes.
Here the tribe config:
```
tribe.t1.cluster.name: appliance_bu-01
tribe.t1.discovery.zen.ping.unicast.hosts: ["bu-01"]
```
The tribe operates normally when I create indices and making query requests. 
But if I close an index I will se a null pointer exception in the log file, and it stops working properly (e.g. I can see the cluster state, but some query fails).
Here a simple test:

on the master node:
```
curl -XPUT "http://localhost:9200/movies/movie/2" -d'
{
    "title": "The Godfather",
    "director": "Francis Ford Coppola",
    "year": 1972
}'
{"_index":"movies","_type":"movie","_id":"2","_version":1,"created":true}

curl -XPOST "http://localhost:9200/movies/_close"
{"acknowledged":true}
```

on the tribe node:
```
tail -f /var/log/elasticsearch/elasticsearch.log

[2014-06-05 10:53:09,539][INFO ][tribe                    ] [Lord Pumpkin] [t1] adding index [movies]
[2014-06-05 10:54:33,140][WARN ][tribe                    ] [Lord Pumpkin] failed to process [cluster event from t1, zen-disco-receive(from master [[Cornelius van Lunt][ZYRaI1BMQ0avMdyxCSMfAg][bu-01][inet[/*myipaddress*:9300]]{data=false, master=true}])]
java.lang.NullPointerException
	at org.elasticsearch.cluster.routing.RoutingTable$Builder.add(RoutingTable.java:400)
	at org.elasticsearch.tribe.TribeService$TribeClusterStateListener$1.execute(TribeService.java:297)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:309)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:134)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

```

my ES version is the same on each node:
```
{
  "status" : 200,
  "name" : "Lord Pumpkin",
  "version" : {
    "number" : "1.2.0",
    "build_hash" : "c82387f290c21505f781c695f365d0ef4098b272",
    "build_timestamp" : "2014-05-22T12:49:13Z",
    "build_snapshot" : false,
    "lucene_version" : "4.8"
  },
  "tagline" : "You Know, for Search"
}
```

**Comment by smorovic** [comment]
I managed to fix this in 1.4.2 codebase (this is unchanged in current master).
Tribe needs to check index close state and do the same as if it was deleted:

```diff
--- bak/elasticsearch-1.4.2/src/main/java/org/elasticsearch/tribe/TribeService.java	2014-12-16 15:10:48.000000000 +0100
+++ ./elasticsearch-1.4.2/src/main/java/org/elasticsearch/tribe/TribeService.java	2015-01-07 18:15:57.000000000 +0100
@@ -259,6 +259,9 @@
                             if (tribeIndex == null) {
                                 logger.info("[{}] removing index [{}]", tribeName, index.index());
                                 removeIndex(blocks, metaData, routingTable, index);
+                            } else if (tribeIndex.state() == IndexMetaData.State.CLOSE) {
+                                logger.info("[{}] removing closed index [{}]", tribeName, index.index());
+                                removeIndex(blocks, metaData, routingTable, index);
                             } else {
                                 // always make sure to update the metadata and routing table, in case
                                 // there are changes in them (new mapping, shards moving from initializing to started)
```

**Comment by clintongormley** [comment]
Hi @smorovic 

Thanks for looking into this.  Would you like to send a PR with your fix? Please could you also add some tests.

thanks

**Comment by smorovic** [comment]
I was going to make a PR with a test case for this fix, but you were faster in getting it done.
Thanks for taking care of it!

**Comment by javanna** [comment]
Hi @smorovic indeed your fix looked good, it was just a matter of testing it. Thanks anyway and sorry to hear you were working on this, I didn't get that.

**Comment by smorovic** [comment]
Hi @javanna, no worries, I didn't do much there. I was adding a couple of lines with "prepareClose() and prepareOpen() calls in the test. Your test cases are certainly more extensive than what I was doing.
