### ISSUE TITLE
Client nodes don't join cluster back post OOM exception

### ISSUE THREAD

**Issue by satishmallik** [elasticsearch/elasticsearch#8451]
In our setup we are always seeing when client nodes throw OOM, it is booted out of cluster. It is never able to join cluster back post OOM exception.

We saw the following from logs

java.lang.OutOfMemoryError: Java heap space
	at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:57)
	at java.nio.ByteBuffer.allocate(ByteBuffer.java:331)
	at sun.nio.cs.StreamEncoder.<init>(StreamEncoder.java:195)
	at sun.nio.cs.StreamEncoder.<init>(StreamEncoder.java:175)
	at sun.nio.cs.StreamEncoder.forOutputStreamWriter(StreamEncoder.java:68)
	at java.io.OutputStreamWriter.<init>(OutputStreamWriter.java:133)
	at java.io.PrintStream.<init>(PrintStream.java:111)
	at java.io.PrintStream.<init>(PrintStream.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:384)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:473)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:203)
	at sun.net.www.http.HttpClient.New(HttpClient.java:290)
	at sun.net.www.http.HttpClient.New(HttpClient.java:306)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:995)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:931)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:849)
	at org.elasticsearch.marvel.agent.exporter.ESExporter.openConnection(ESExporter.java:325)
	at org.elasticsearch.marvel.agent.exporter.ESExporter.openExportingConnection(ESExporter.java:182)
	at org.elasticsearch.marvel.agent.exporter.ESExporter.exportXContent(ESExporter.java:248)
	at org.elasticsearch.marvel.agent.exporter.ESExporter.exportNodeStats(ESExporter.java:130)
	at org.elasticsearch.marvel.agent.AgentService$ExportingWorker.exportNodeStats(AgentService.java:349)
	at org.elasticsearch.marvel.agent.AgentService$ExportingWorker.run(AgentService.java:236)
	at java.lang.Thread.run(Thread.java:724)

...............
[2014-11-04 09:34:50,844][DEBUG][action.search.type       ] [ES-NODE-Q02] [3312] Failed to execute fetch phase
org.elasticsearch.transport.NodeDisconnectedException: [ES-NODE-D02][inet[/10.0.0.8:9300]][search/phase/fetch/id] disconnected
...

[2014-11-04 09:41:35,957][DEBUG][action.admin.indices.alias.get] [ES-NODE-Q02] connection exception while trying to forward request to master node [[ES-NODE-M01][K13SBxlOQ06-axx0_UL1bg][es-node-m01][inet[/10.0.0.10:9300]]{updateDomain=0, tag=masternode, data=false, faultDomain=0, master=true}], scheduling a retry. Error: [org.elasticsearch.transport.NodeDisconnectedException: [ES-NODE-M01][inet[/10.0.0.10:9300]][indices/get/aliases] disconnected]

Post OOM exception client node is never able to join cluster back. We needed to restart es service on client node to get this node join back to cluster.

Is it a known issue? Is it expected behavior?

**Comment by clintongormley** [comment]
No more info provided. Closing
