### ISSUE TITLE
Making ES more robust against "corrupt" nodes or node failures causing Master OOM

### ISSUE THREAD

**Issue by bluelu** [elasticsearch/elasticsearch#8881]
Our master node failed with an OOM last night.

We had one node which couldn't apply the cluster state and had this entry in the node log for each master update:

    [2014-12-10 12:41:01,127][WARN ][cluster.service          ] [node] failed to apply updated cluster state:
    .. complete cluster state...
    org.elasticsearch.indices.IndexCreationException: [index] failed to create index
            at org.elasticsearch.indices.InternalIndicesService.createIndex(InternalIndicesService.java:303)
            at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyNewIndices(IndicesClusterStateService.java:310)
            at org.elasticsearch.indices.cluster.IndicesClusterStateService.clusterChanged(IndicesClusterStateService.java:179)
            at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:431)
            at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:153)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
            at java.lang.Thread.run(Thread.java:745)
    Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.elasticsearch.index.codec.docvaluesformat.DocValuesFormats
            at org.elasticsearch.index.codec.CodecModule.configureDocValuesFormats(CodecModule.java:166)
            at org.elasticsearch.index.codec.CodecModule.configure(CodecModule.java:179)
            at org.elasticsearch.common.inject.AbstractModule.configure(AbstractModule.java:60)
            at org.elasticsearch.common.inject.spi.Elements$RecordingBinder.install(Elements.java:204)
            at org.elasticsearch.common.inject.spi.Elements.getElements(Elements.java:85)
            at org.elasticsearch.common.inject.InjectorShell$Builder.build(InjectorShell.java:130)
            at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:99)
            at org.elasticsearch.common.inject.InjectorImpl.createChildInjector(InjectorImpl.java:131)
            at org.elasticsearch.common.inject.ModulesBuilder.createChildInjector(ModulesBuilder.java:69)
            at org.elasticsearch.indices.InternalIndicesService.createIndex(InternalIndicesService.java:299)
            ... 7 more

I don't see any cluster state related exception in the master regarding the update on the cluster state, but other exceptions regarding that node: (might be unrelated):

    org.elasticsearch.transport.RemoteTransportException: [node][inet[/node:9300]][internal:cluster/nodes/indices/shard/store[n]]
    Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.apache.lucene.codecs.Codec
            at org.apache.lucene.index.SegmentInfos.read(SegmentInfos.java:356)
            at org.apache.lucene.index.SegmentInfos$1.doBody(SegmentInfos.java:454)
            at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:906)
            at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:752)
            at org.apache.lucene.index.SegmentInfos.read(SegmentInfos.java:450)
            at org.elasticsearch.common.lucene.Lucene.readSegmentInfos(Lucene.java:85)
            at org.elasticsearch.index.store.Store.readSegmentsInfo(Store.java:124)
            at org.elasticsearch.index.store.Store.access$400(Store.java:80)
            at org.elasticsearch.index.store.Store$MetadataSnapshot.buildMetadata(Store.java:575)
            at org.elasticsearch.index.store.Store$MetadataSnapshot.<init>(Store.java:568)
            at org.elasticsearch.index.store.Store.readMetadataSnapshot(Store.java:317)
            at org.elasticsearch.indices.store.TransportNodesListShardStoreMetaData.listStoreMetaData(TransportNodesListShardStoreMetaData.java:182)
            at org.elasticsearch.indices.store.TransportNodesListShardStoreMetaData.nodeOperation(TransportNodesListShardStoreMetaData.java:138)
            at org.elasticsearch.indices.store.TransportNodesListShardStoreMetaData.nodeOperation(TransportNodesListShardStoreMetaData.java:59)
            at org.elasticsearch.action.support.nodes.TransportNodesOperationAction$NodeTransportHandler.messageReceived(TransportNodesOperationAction.java:278)
            at org.elasticsearch.action.support.nodes.TransportNodesOperationAction$NodeTransportHandler.messageReceived(TransportNodesOperationAction.java:269)
            at org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler.run(MessageChannelHandler.java:275)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
            at java.lang.Thread.run(Thread.java:745)

I haven't looked at the heapdump of the master node (If needed I can have a look), but I suspect that due to the failed cluster the connection buffer will just grow until there is no space left.

It turned out the node had a corrupt jar, restarting didn't help and caused the heap to grow, and we had to reploy in order to fix it. Killing the node reduced the heap of the master node again.

We will add this to our monitoring so it won't appear again.

Still an ES fix (e.g. triggering node restart, shutdown on node, or reducing the max buffer for the connection would be great) making it more robust against such failures would be great.

**Comment by clintongormley** [comment]
@miccon any more news here?

**Comment by miccon** [comment]
@clintongormley no news to report here. The issue did not reappear on our cluster.

**Comment by clintongormley** [comment]
thanks @miccon - I'll close this issue for now then

**Comment by njustyq** [comment]
I have a similar problems @bleskes  @miccon , Can you check it out for me. 
 https://github.com/elastic/elasticsearch/issues/50241

**Comment by njustyq** [comment]
@clintongormley @bleskes @miccon would you please check it out for me? 
#50241

**Comment by clintongormley** [comment]
@njustyq don't ping people like that - it is rude

**Comment by njustyq** [comment]
> @njustyq don't ping people like that - it is rude
sorry，i'm just a little anxious...
