### ISSUE TITLE
Multi Point Geohash Aggregation

### ISSUE THREAD

**Issue by justnick21** [elasticsearch/elasticsearch#8886]
Hello,

I am currently working with some geodata which I aggregate using a geohash aggregation. 

It seems multipoints are causing a problem with the aggregation.

I'm not even sure what the behaviour would default too if there were multiple points to be aggregated by geohash..

I have fixed the problem by calculating a single centroid and aggregating by that.

I thought it was a bit odd (and initially quite confusing) that I got a ArrayIndexOutOfBoundsException, Perhaps the error message could be clearer?

Error below:
```
[2014-12-10 17:07:17,222][DEBUG][action.search.type       ] [Trevor Fitzroy] [incidents][3], node[titfofnQT1aYovIoqT1cTA], [P], s[STARTED]: Failed to execute [org.elasticsearch.action.search.SearchRequest@3eb68f0e] lastShard [true]
org.elasticsearch.search.query.QueryPhaseExecutionException: [incidents][3]: query[ConstantScore(cache(org.elasticsearch.index.search.nested.NonNestedDocsFilter@749ccf3a))],from[0],size[10]: Query Failed [Failed to execute main query]
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:163)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:275)
	at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:231)
	at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:228)
	at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:559)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at org.elasticsearch.search.aggregations.bucket.geogrid.GeoHashGridParser$GeoGridFactory$CellValues.setDocument(GeoHashGridParser.java:154)
	at org.elasticsearch.search.aggregations.bucket.geogrid.GeoHashGridAggregator.collect(GeoHashGridAggregator.java:73)
	at org.elasticsearch.search.aggregations.AggregatorFactories$1.collect(AggregatorFactories.java:114)
	at org.elasticsearch.search.aggregations.bucket.BucketsAggregator.collectBucketNoCounts(BucketsAggregator.java:74)
	at org.elasticsearch.search.aggregations.bucket.BucketsAggregator.collectExistingBucket(BucketsAggregator.java:63)
	at org.elasticsearch.search.aggregations.bucket.BucketsAggregator.collectBucket(BucketsAggregator.java:55)
	at org.elasticsearch.search.aggregations.bucket.filter.FilterAggregator.collect(FilterAggregator.java:61)
	at org.elasticsearch.search.aggregations.AggregationPhase$AggregationsCollector.collect(AggregationPhase.java:161)
	at org.elasticsearch.common.lucene.MultiCollector.collect(MultiCollector.java:60)
	at org.apache.lucene.search.Weight$DefaultBulkScorer.scoreAll(Weight.java:193)
	at org.apache.lucene.search.Weight$DefaultBulkScorer.score(Weight.java:163)
	at org.apache.lucene.search.BulkScorer.score(BulkScorer.java:35)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:621)
	at org.elasticsearch.search.internal.ContextIndexSearcher.search(ContextIndexSearcher.java:191)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:309)
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:117)
	... 7 more
```

**Comment by clintongormley** [comment]
@justnick21 any more info here, otherwise we'll close this ticket

**Comment by justnick21** [comment]
@clintongormley if i manage to reproduce it on a a small test dataset i will reopen or raise again. thanks.

**Comment by clintongormley** [comment]
thanks @justnick21 

I'll close this issue for now then
