### ISSUE TITLE
SearchParseException  version 1.4.2 

### ISSUE THREAD

**Issue by laurusCN** [elasticsearch/elasticsearch#9153]
search query: 

{"query":{"bool":{"must":[{"query_string":{"default_field":"_all","query":"NSUN/NSUN"}}],"must_not":[],"should":[]}},"from":0,"size":10,"sort":[],"facets":{}}

 error log:
```error
[2015-01-06 13:51:47,209][DEBUG][action.search.type       ] [Angel Salvadore] [brand][0], node[zYx-C-ciSAuacDsiSPvMLQ], [P], s[STARTED]: Failed to execute [org.elasticsearch.action.search.SearchRequest@773d3f4a] lastShard [true]
org.elasticsearch.search.SearchParseException: [brand][0]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"bool":{"must":[{"query_string":{"default_field":"_all","query":"NSUN/NSUN"}}],"must_not":[],"should":[]}},"from":0,"size":10,"sort":[],"facets":{}}]]
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:681)
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:537)
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:509)
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:264)
        at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:231)
        at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:228)
        at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:559)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.index.query.QueryParsingException: [brand] Failed to parse query [NSUN/NSUN]
        at org.elasticsearch.index.query.QueryStringQueryParser.parse(QueryStringQueryParser.java:240)
        at org.elasticsearch.index.query.QueryParseContext.parseInnerQuery(QueryParseContext.java:277)
        at org.elasticsearch.index.query.BoolQueryParser.parse(BoolQueryParser.java:93)
        at org.elasticsearch.index.query.QueryParseContext.parseInnerQuery(QueryParseContext.java:277)
        at org.elasticsearch.index.query.IndexQueryParserService.innerParse(IndexQueryParserService.java:382)
        at org.elasticsearch.index.query.IndexQueryParserService.parse(IndexQueryParserService.java:281)
        at org.elasticsearch.index.query.IndexQueryParserService.parse(IndexQueryParserService.java:276)
        at org.elasticsearch.search.query.QueryParseElement.parse(QueryParseElement.java:33)
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:665)
        ... 9 more
Caused by: org.apache.lucene.queryparser.classic.ParseException: Cannot parse 'NSUN/NSUN': Lexical error at line 1, column 10.  Encountered: <EOF> after : "/NSUN"
        at org.apache.lucene.queryparser.classic.QueryParserBase.parse(QueryParserBase.java:133)
        at org.apache.lucene.queryparser.classic.MapperQueryParser.parse(MapperQueryParser.java:882)
        at org.elasticsearch.index.query.QueryStringQueryParser.parse(QueryStringQueryParser.java:223)
        ... 17 more
Caused by: org.apache.lucene.queryparser.classic.TokenMgrError: Lexical error at line 1, column 10.  Encountered: <EOF> after : "/NSUN"
        at org.apache.lucene.queryparser.classic.QueryParserTokenManager.getNextToken(QueryParserTokenManager.java:1133)
        at org.apache.lucene.queryparser.classic.QueryParser.jj_scan_token(QueryParser.java:601)
        at org.apache.lucene.queryparser.classic.QueryParser.jj_3R_2(QueryParser.java:484)
        at org.apache.lucene.queryparser.classic.QueryParser.jj_3_1(QueryParser.java:491)
        at org.apache.lucene.queryparser.classic.QueryParser.jj_2_1(QueryParser.java:477)
        at org.apache.lucene.queryparser.classic.QueryParser.Clause(QueryParser.java:228)
        at org.apache.lucene.queryparser.classic.QueryParser.Query(QueryParser.java:183)
        at org.apache.lucene.queryparser.classic.QueryParser.TopLevelQuery(QueryParser.java:172)
        at org.apache.lucene.queryparser.classic.QueryParserBase.parse(QueryParserBase.java:123)
        ... 19 more
[2015-01-06 13:51:47,210][DEBUG][action.search.type       ] [Angel Salvadore] [brand][4], node[zYx-C-ciSAuacDsiSPvMLQ], [P], s[STARTED]: Failed to execute [org.elasticsearch.action.search.SearchRequest@773d3f4a] lastShard [true]
org.elasticsearch.search.SearchParseException: [brand][4]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"bool":{"must":[{"query_string":{"default_field":"_all","query":"NSUN/NSUN"}}],"must_not":[],"should":[]}},"from":0,"size":10,"sort":[],"facets":{}}]]
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:681)
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:537)
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:509)
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:264)
        at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:231)
        at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:228)
        at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:559)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.index.query.QueryParsingException: [brand] Failed to parse query [NSUN/NSUN]
        at org.elasticsearch.index.query.QueryStringQueryParser.parse(QueryStringQueryParser.java:240)
        at org.elasticsearch.index.query.QueryParseContext.parseInnerQuery(QueryParseContext.java:277)
        at org.elasticsearch.index.query.BoolQueryParser.parse(BoolQueryParser.java:93)
        at org.elasticsearch.index.query.QueryParseContext.parseInnerQuery(QueryParseContext.java:277)
        at org.elasticsearch.index.query.IndexQueryParserService.innerParse(IndexQueryParserService.java:382)
        at org.elasticsearch.index.query.IndexQueryParserService.parse(IndexQueryParserService.java:281)
        at org.elasticsearch.index.query.IndexQueryParserService.parse(IndexQueryParserService.java:276)
        at org.elasticsearch.search.query.QueryParseElement.parse(QueryParseElement.java:33)
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:665)
        ... 9 more
Caused by: org.apache.lucene.queryparser.classic.ParseException: Cannot parse 'NSUN/NSUN': Lexical error at line 1, column 10.  Encountered: <EOF> after : "/NSUN"
        at org.apache.lucene.queryparser.classic.QueryParserBase.parse(QueryParserBase.java:133)
        at org.apache.lucene.queryparser.classic.MapperQueryParser.parse(MapperQueryParser.java:882)
        at org.elasticsearch.index.query.QueryStringQueryParser.parse(QueryStringQueryParser.java:223)
        ... 17 more
Caused by: org.apache.lucene.queryparser.classic.TokenMgrError: Lexical error at line 1, column 10.  Encountered: <EOF> after : "/NSUN"
        at org.apache.lucene.queryparser.classic.QueryParserTokenManager.getNextToken(QueryParserTokenManager.java:1133)
        at org.apache.lucene.queryparser.classic.QueryParser.jj_scan_token(QueryParser.java:601)
        at org.apache.lucene.queryparser.classic.QueryParser.jj_3R_2(QueryParser.java:484)
        at org.apache.lucene.queryparser.classic.QueryParser.jj_3_1(QueryParser.java:491)
        at org.apache.lucene.queryparser.classic.QueryParser.jj_2_1(QueryParser.java:477)
        at org.apache.lucene.queryparser.classic.QueryParser.Clause(QueryParser.java:228)
        at org.apache.lucene.queryparser.classic.QueryParser.Query(QueryParser.java:183)
        at org.apache.lucene.queryparser.classic.QueryParser.TopLevelQuery(QueryParser.java:172)
        at org.apache.lucene.queryparser.classic.QueryParserBase.parse(QueryParserBase.java:123)
        ... 19 more
[2015-01-06 13:51:47,209][DEBUG][action.search.type       ] [Angel Salvadore] [brand][3], node[zYx-C-ciSAuacDsiSPvMLQ], [P], s[STARTED]: Failed to execute [org.elasticsearch.action.search.SearchRequest@773d3f4a] lastShard [true]
org.elasticsearch.search.SearchParseException: [brand][3]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"bool":{"must":[{"query_string":{"default_field":"_all","query":"NSUN/NSUN"}}],"must_not":[],"should":[]}},"from":0,"size":10,"sort":[],"facets":{}}]]
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:681)
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:537)
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:509)
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:264)
        at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:231)
        at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:228)
        at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:559)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.index.query.QueryParsingException: [brand] Failed to parse query [NSUN/NSUN]
        at org.elasticsearch.index.query.QueryStringQueryParser.parse(QueryStringQueryParser.java:240)
        at org.elasticsearch.index.query.QueryParseContext.parseInnerQuery(QueryParseContext.java:277)
        at org.elasticsearch.index.query.BoolQueryParser.parse(BoolQueryParser.java:93)
        at org.elasticsearch.index.query.QueryParseContext.parseInnerQuery(QueryParseContext.java:277)
        at org.elasticsearch.index.query.IndexQueryParserService.innerParse(IndexQueryParserService.java:382)
        at org.elasticsearch.index.query.IndexQueryParserService.parse(IndexQueryParserService.java:281)
        at org.elasticsearch.index.query.IndexQueryParserService.parse(IndexQueryParserService.java:276)
        at org.elasticsearch.search.query.QueryParseElement.parse(QueryParseElement.java:33)
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:665)
        ... 9 more
Caused by: org.apache.lucene.queryparser.classic.ParseException: Cannot parse 'NSUN/NSUN': Lexical error at line 1, column 10.  Encountered: <EOF> after : "/NSUN"
        at org.apache.lucene.queryparser.classic.QueryParserBase.parse(QueryParserBase.java:133)
        at org.apache.lucene.queryparser.classic.MapperQueryParser.parse(MapperQueryParser.java:882)
        at org.elasticsearch.index.query.QueryStringQueryParser.parse(QueryStringQueryParser.java:223)
        ... 17 more
Caused by: org.apache.lucene.queryparser.classic.TokenMgrError: Lexical error at line 1, column 10.  Encountered: <EOF> after : "/NSUN"
        at org.apache.lucene.queryparser.classic.QueryParserTokenManager.getNextToken(QueryParserTokenManager.java:1133)
        at org.apache.lucene.queryparser.classic.QueryParser.jj_scan_token(QueryParser.java:601)
        at org.apache.lucene.queryparser.classic.QueryParser.jj_3R_2(QueryParser.java:484)
        at org.apache.lucene.queryparser.classic.QueryParser.jj_3_1(QueryParser.java:491)
        at org.apache.lucene.queryparser.classic.QueryParser.jj_2_1(QueryParser.java:477)
        at org.apache.lucene.queryparser.classic.QueryParser.Clause(QueryParser.java:228)
        at org.apache.lucene.queryparser.classic.QueryParser.Query(QueryParser.java:183)
        at org.apache.lucene.queryparser.classic.QueryParser.TopLevelQuery(QueryParser.java:172)
        at org.apache.lucene.queryparser.classic.QueryParserBase.parse(QueryParserBase.java:123)
        ... 19 more
[2015-01-06 13:51:47,211][DEBUG][action.search.type       ] [Angel Salvadore] [brand][2], node[zYx-C-ciSAuacDsiSPvMLQ], [P], s[STARTED]: Failed to execute [org.elasticsearch.action.search.SearchRequest@773d3f4a] lastShard [true]
org.elasticsearch.search.SearchParseException: [brand][2]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"bool":{"must":[{"query_string":{"default_field":"_all","query":"NSUN/NSUN"}}],"must_not":[],"should":[]}},"from":0,"size":10,"sort":[],"facets":{}}]]
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:681)
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:537)
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:509)
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:264)
        at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:231)
        at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:228)
        at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:559)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.index.query.QueryParsingException: [brand] Failed to parse query [NSUN/NSUN]
        at org.elasticsearch.index.query.QueryStringQueryParser.parse(QueryStringQueryParser.java:240)
        at org.elasticsearch.index.query.QueryParseContext.parseInnerQuery(QueryParseContext.java:277)
        at org.elasticsearch.index.query.BoolQueryParser.parse(BoolQueryParser.java:93)
        at org.elasticsearch.index.query.QueryParseContext.parseInnerQuery(QueryParseContext.java:277)
        at org.elasticsearch.index.query.IndexQueryParserService.innerParse(IndexQueryParserService.java:382)
        at org.elasticsearch.index.query.IndexQueryParserService.parse(IndexQueryParserService.java:281)
        at org.elasticsearch.index.query.IndexQueryParserService.parse(IndexQueryParserService.java:276)
        at org.elasticsearch.search.query.QueryParseElement.parse(QueryParseElement.java:33)
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:665)
        ... 9 more
Caused by: org.apache.lucene.queryparser.classic.ParseException: Cannot parse 'NSUN/NSUN': Lexical error at line 1, column 10.  Encountered: <EOF> after : "/NSUN"
        at org.apache.lucene.queryparser.classic.QueryParserBase.parse(QueryParserBase.java:133)
        at org.apache.lucene.queryparser.classic.MapperQueryParser.parse(MapperQueryParser.java:882)
        at org.elasticsearch.index.query.QueryStringQueryParser.parse(QueryStringQueryParser.java:223)
        ... 17 more
Caused by: org.apache.lucene.queryparser.classic.TokenMgrError: Lexical error at line 1, column 10.  Encountered: <EOF> after : "/NSUN"
        at org.apache.lucene.queryparser.classic.QueryParserTokenManager.getNextToken(QueryParserTokenManager.java:1133)
        at org.apache.lucene.queryparser.classic.QueryParser.jj_scan_token(QueryParser.java:601)
        at org.apache.lucene.queryparser.classic.QueryParser.jj_3R_2(QueryParser.java:484)
        at org.apache.lucene.queryparser.classic.QueryParser.jj_3_1(QueryParser.java:491)
        at org.apache.lucene.queryparser.classic.QueryParser.jj_2_1(QueryParser.java:477)
        at org.apache.lucene.queryparser.classic.QueryParser.Clause(QueryParser.java:228)
        at org.apache.lucene.queryparser.classic.QueryParser.Query(QueryParser.java:183)
        at org.apache.lucene.queryparser.classic.QueryParser.TopLevelQuery(QueryParser.java:172)
        at org.apache.lucene.queryparser.classic.QueryParserBase.parse(QueryParserBase.java:123)
        ... 19 more
[2015-01-06 13:51:47,211][DEBUG][action.search.type       ] [Angel Salvadore] [brand][1], node[zYx-C-ciSAuacDsiSPvMLQ], [P], s[STARTED]: Failed to execute [org.elasticsearch.action.search.SearchRequest@773d3f4a]
org.elasticsearch.search.SearchParseException: [brand][1]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"bool":{"must":[{"query_string":{"default_field":"_all","query":"NSUN/NSUN"}}],"must_not":[],"should":[]}},"from":0,"size":10,"sort":[],"facets":{}}]]
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:681)
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:537)
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:509)
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:264)
        at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:231)
        at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:228)
        at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:559)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.index.query.QueryParsingException: [brand] Failed to parse query [NSUN/NSUN]
        at org.elasticsearch.index.query.QueryStringQueryParser.parse(QueryStringQueryParser.java:240)
        at org.elasticsearch.index.query.QueryParseContext.parseInnerQuery(QueryParseContext.java:277)
        at org.elasticsearch.index.query.BoolQueryParser.parse(BoolQueryParser.java:93)
        at org.elasticsearch.index.query.QueryParseContext.parseInnerQuery(QueryParseContext.java:277)
        at org.elasticsearch.index.query.IndexQueryParserService.innerParse(IndexQueryParserService.java:382)
        at org.elasticsearch.index.query.IndexQueryParserService.parse(IndexQueryParserService.java:281)
        at org.elasticsearch.index.query.IndexQueryParserService.parse(IndexQueryParserService.java:276)
        at org.elasticsearch.search.query.QueryParseElement.parse(QueryParseElement.java:33)
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:665)
        ... 9 more
Caused by: org.apache.lucene.queryparser.classic.ParseException: Cannot parse 'NSUN/NSUN': Lexical error at line 1, column 10.  Encountered: <EOF> after : "/NSUN"
        at org.apache.lucene.queryparser.classic.QueryParserBase.parse(QueryParserBase.java:133)
        at org.apache.lucene.queryparser.classic.MapperQueryParser.parse(MapperQueryParser.java:882)
        at org.elasticsearch.index.query.QueryStringQueryParser.parse(QueryStringQueryParser.java:223)
        ... 17 more
Caused by: org.apache.lucene.queryparser.classic.TokenMgrError: Lexical error at line 1, column 10.  Encountered: <EOF> after : "/NSUN"
        at org.apache.lucene.queryparser.classic.QueryParserTokenManager.getNextToken(QueryParserTokenManager.java:1133)
        at org.apache.lucene.queryparser.classic.QueryParser.jj_scan_token(QueryParser.java:601)
        at org.apache.lucene.queryparser.classic.QueryParser.jj_3R_2(QueryParser.java:484)
        at org.apache.lucene.queryparser.classic.QueryParser.jj_3_1(QueryParser.java:491)
        at org.apache.lucene.queryparser.classic.QueryParser.jj_2_1(QueryParser.java:477)
        at org.apache.lucene.queryparser.classic.QueryParser.Clause(QueryParser.java:228)
        at org.apache.lucene.queryparser.classic.QueryParser.Query(QueryParser.java:183)
        at org.apache.lucene.queryparser.classic.QueryParser.TopLevelQuery(QueryParser.java:172)
        at org.apache.lucene.queryparser.classic.QueryParserBase.parse(QueryParserBase.java:123)
        ... 19 more
[2015-01-06 13:51:47,215][DEBUG][action.search.type       ] [Angel Salvadore] All shards failed for phase: [query]
```

**Comment by johtani** [comment]
Hi, @laurusCN 

Please ask questions like these on the mailing list http://elasticsearch.org/community. The GitHub issues list is for bug reports and feature requests. 

You may want to read this: http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#_reserved_characters
