### ISSUE TITLE
Marvel - Error connecting to [:9200]

### ISSUE THREAD

**Issue by bittusarkar** [elasticsearch/elasticsearch#9236]
When I restarted one of the ES nodes in a cluster, I see the following error stack as soon as the node is restarted.
```
[2015-01-10 05:19:02,978][ERROR][marvel.agent.exporter    ] [QUERY_NODE_01] error connecting to [:9200]
java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:378)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:473)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:203)
	at sun.net.www.http.HttpClient.New(HttpClient.java:290)
	at sun.net.www.http.HttpClient.New(HttpClient.java:306)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:995)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:931)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:849)
	at org.elasticsearch.marvel.agent.exporter.ESExporter.openConnection(ESExporter.java:325)
	at org.elasticsearch.marvel.agent.exporter.ESExporter.openConnection(ESExporter.java:295)
	at org.elasticsearch.marvel.agent.exporter.ESExporter.checkAndUploadIndexTemplate(ESExporter.java:384)
	at org.elasticsearch.marvel.agent.exporter.ESExporter.openExportingConnection(ESExporter.java:174)
	at org.elasticsearch.marvel.agent.exporter.ESExporter.exportXContent(ESExporter.java:248)
	at org.elasticsearch.marvel.agent.exporter.ESExporter.exportNodeStats(ESExporter.java:130)
	at org.elasticsearch.marvel.agent.AgentService$ExportingWorker.exportNodeStats(AgentService.java:349)
	at org.elasticsearch.marvel.agent.AgentService$ExportingWorker.run(AgentService.java:236)
	at java.lang.Thread.run(Thread.java:724)
```

Errors like ```error connecting to [localhost:9200]``` have been discussed in several issues here and I understand why it occurs but I've never seen ```error connecting to [:9200]```. Can you help in understanding why I might have seen this error and if it can be avoided?

**Comment by bleskes** [comment]
Which version of marvel do you use? Does your local Es node listen on 9200? Any custom settings to the marvel.agent.exporter.es.hosts? I suspect that what thy resolve to.

**Comment by bittusarkar** [comment]
I use Marvel 1.2.1. You are spot on with respect to the root cause. I checked the value of `marvel.agent.exporter.es.hosts` and it was set to `[":9200"]`. Not sure how that happened. Anyways, if I set it to `[]`, it would log on the same node right?

**Comment by bleskes** [comment]
In that case I would just remove the line. If you run on a custom port you can upgrade to marvel 1.3 or you'll have to change the settings to that.

**Comment by bittusarkar** [comment]
Thanks @bleskes. This helps a lot!

**Comment by dineshbugide** [comment]
I am using marvel 2.0.0 with elasticsearch 2.0.0 but my marvel is not starting

**Comment by dadoonet** [comment]
@dineshbugide send your questions to discuss.elastic.co and provide all details there.

Also please read the marvel documentation as it changed a lot in 2.0.
