### ISSUE TITLE
Elastic search 1.4.2 data path issue

### ISSUE THREAD

**Issue by dobariya** [elasticsearch/elasticsearch#9249]
I am using UNC path to store the data eg: \pc1\data.
This works perfect in version 1.3.4 but after I upgrade it to 1.3.7 or 1.4.2 it started give me error

Below is the error log

[2015-01-12 16:03:33,087][INFO ][node ] [master1] version[1.3.7], pid[7068], build[3042293/2014-12-16T13:59:32Z]
[2015-01-12 16:03:33,087][INFO ][node ] [master1] initializing ...
[2015-01-12 16:03:33,102][INFO ][plugins ] [master1] loaded [], sites []
[2015-01-12 16:03:36,249][INFO ][node ] [master1] initialized
[2015-01-12 16:03:36,249][INFO ][node ] [master1] starting ...
[2015-01-12 16:03:36,514][INFO ][transport ] [master1] bound_address {inet[/0:0:0:0:0:0:0:0:9300]}, publish_address {inet[/192.168.2.101:9300]}
[2015-01-12 16:03:36,795][INFO ][discovery ] [master1] local1/xBx3MDWZT--1dKhACi3KSA
[2015-01-12 16:03:39,844][INFO ][cluster.service ] [master1] new_master [master1][xBx3MDWZT--1dKhACi3KSA][dell13][inet[/192.168.2.101:9300]]{master=true}, reason: zen-disco-join (elected_as_master)
[2015-01-12 16:03:39,901][INFO ][http ] [master1] bound_address {inet[/0:0:0:0:0:0:0:0:9200]}, publish_address {inet[/192.168.2.101:9200]}
[2015-01-12 16:03:39,901][INFO ][node ] [master1] started
[2015-01-12 16:03:39,964][INFO ][gateway ] [master1] recovered [0] indices into cluster_state
[2015-01-12 16:04:09,878][DEBUG][action.admin.cluster.node.stats] [master1] failed to execute on node [xBx3MDWZT--1dKhACi3KSA]
java.lang.IllegalStateException: Free bytes [-1] cannot be less than 0 or greater than total bytes [-1]
at org.elasticsearch.cluster.DiskUsage.(DiskUsage.java:32)
at org.elasticsearch.cluster.InternalClusterInfoService$ClusterInfoUpdateJob$1.onResponse(InternalClusterInfoService.java:279)
at org.elasticsearch.cluster.InternalClusterInfoService$ClusterInfoUpdateJob$1.onResponse(InternalClusterInfoService.java:260)
at org.elasticsearch.action.support.nodes.TransportNodesOperationAction$AsyncAction.finishHim(TransportNodesOperationAction.java:221)
at org.elasticsearch.action.support.nodes.TransportNodesOperationAction$AsyncAction.onOperation(TransportNodesOperationAction.java:196)
at org.elasticsearch.action.support.nodes.TransportNodesOperationAction$AsyncAction.access$900(TransportNodesOperationAction.java:96)
at org.elasticsearch.action.support.nodes.TransportNodesOperationAction$AsyncAction$2.run(TransportNodesOperationAction.java:140)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)

**Comment by dakrone** [comment]
@dobariya thanks for reporting this, can you tell me what kind of filesystem `\pc1\data` is? Is it a samba share or local disk?

**Comment by dobariya** [comment]
@dakrone thanks for quick response. we have windows environment ,file system is  NTFS

**Comment by dakrone** [comment]
@dobariya also, as a workaround in the meantime, if you are _not_ using the [disk-based shard allocation](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/index-modules-allocation.html#disk) you can disable this by setting `cluster.routing.allocation.disk.threshold_enabled` to `false` and the disk usages will not be checked.

**Comment by dobariya** [comment]
@dakrone Thanks for the quick response and this resolved my issue.
I have one more question regarding version upgrade.
I have indexed 2 million data using version 1.3.4 and now i want to grab the latest elasticsearch version.Can I directly upgrade it by just replacing the existing setup elasticsearch-1.3.4 folder to the latest version or do I have to configure other settings also?

**Comment by dakrone** [comment]
> Can I directly upgrade it by just replacing the existing setup elasticsearch-1.3.4 folder to the latest version or do I have to configure other settings also?

You should be able to upgrade doing this, however, it would be good to check the release notes for the versions you are skipping to make sure there aren't any breaking changes that will impact you, in particular, if you're upgrading to 1.4.2, you should check the [1.4.0-beta1 release notes](http://www.elasticsearch.org/downloads/1-4-0-beta1/) which lists the breaking changes between 1.3.x and 1.4.x (it is a small list)

**Comment by dobariya** [comment]
Thanks buddy.
can you please guide me in setting up my configuration.
I have 3 nodes
node1:master=true and data=true
node2:master=true and data=false
node3:master=false and data=false

am storing the data on only one single UNC path which i already mentioned the the above comments.All above nodes are pointed to this single UNC path

Please guide whether above nodes setting, all nodes pointing the one single UNC path is a good practice or not
