### ISSUE TITLE
CircuitBreaking Exception: Data Too Large for field parent/chi ld id cache

### ISSUE THREAD

**Issue by bharvidixit** [elasticsearch/elasticsearch#9290]
Hi, I have following cluster configuration:
2 data nodes (RAM: 32GB EACH, HEAP SIZE: 16GB EACH)
3 master nodes 
2 client nodes.

Index has parent child schema.

On one of my data node i have got this exception while indexing.

[2015-01-14 12:26:50,264][ERROR][indices.fielddata.breaker] [data_node1] New used memory 10266147967 [9.5gb] from field [parent/child id cache]
 would be larger than configured breaker: 10266083328 [9.5gb], breaking
[2015-01-14 12:26:50,265][WARN ][index.warmer             ] [data_node1] [es_politics_commonschema_v1.0][0] failed to warm-up fielddata for [_p
arent]
org.elasticsearch.ElasticsearchException: org.elasticsearch.common.breaker.CircuitBreakingException: Data too large, data for field [parent/chi
ld id cache] would be larger than limit of [10266083328/9.5gb]
        at org.elasticsearch.index.fielddata.AbstractIndexFieldData.load(AbstractIndexFieldData.java:79)
        at org.elasticsearch.search.SearchService$FieldDataWarmer$1.run(SearchService.java:814)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)
Caused by: org.elasticsearch.common.util.concurrent.UncheckedExecutionException: org.elasticsearch.common.breaker.CircuitBreakingException: Data too large, data for field [parent/child id cache] would be larger than limit of [10266083328/9.5gb]
        at org.elasticsearch.common.cache.LocalCache$Segment.get(LocalCache.java:2201)
        at org.elasticsearch.common.cache.LocalCache.get(LocalCache.java:3934)
        at org.elasticsearch.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4736)
        at org.elasticsearch.indices.fielddata.cache.IndicesFieldDataCache$IndexFieldCache.load(IndicesFieldDataCache.java:154)
        at org.elasticsearch.index.fielddata.AbstractIndexFieldData.load(AbstractIndexFieldData.java:73)
        ... 4 more
Caused by: org.elasticsearch.common.breaker.CircuitBreakingException: Data too large, data for field [parent/child id cache] would be larger than limit of [10266083328/9.5gb]
        at org.elasticsearch.common.breaker.MemoryCircuitBreaker.circuitBreak(MemoryCircuitBreaker.java:82)
        at org.elasticsearch.common.breaker.MemoryCircuitBreaker.addEstimateBytesAndMaybeBreak(MemoryCircuitBreaker.java:132)
        at org.elasticsearch.index.fielddata.RamAccountingTermsEnum.flush(RamAccountingTermsEnum.java:70)
        at org.elasticsearch.index.fielddata.RamAccountingTermsEnum.next(RamAccountingTermsEnum.java:84)
        at org.elasticsearch.index.fielddata.plain.ParentChildIndexFieldData.loadDirect(ParentChildIndexFieldData.java:112)
        at org.elasticsearch.index.fielddata.plain.ParentChildIndexFieldData.loadDirect(ParentChildIndexFieldData.java:59)
        at org.elasticsearch.indices.fielddata.cache.IndicesFieldDataCache$IndexFieldCache$1.call(IndicesFieldDataCache.java:167)
        at org.elasticsearch.indices.fielddata.cache.IndicesFieldDataCache$IndexFieldCache$1.call(IndicesFieldDataCache.java:154)
        at org.elasticsearch.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4739)
        at org.elasticsearch.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
        at org.elasticsearch.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
        at org.elasticsearch.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
        at org.elasticsearch.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
        ... 8 more

Is it a bug or some other issue.?

Regards
Bharvi

**Comment by clintongormley** [comment]
Hi @bharvidixit 

It's not a bug.  The circuit breaker prevented you from loading more data than you have memory to hold.  I'd suggest adding a node or increasing the amount of heap space (and total RAM) that you have.

**Comment by bharvidixit** [comment]
Thanks a ton @clintongormley

**Comment by ryancutter** [comment]
For future people who come across this issue - adding a node or heap space is certainly the best solution but there is also a setting (indices.breaker.fielddata.limit) which can be overridden [as documented here](http://techieroop.com/circuitbreaking-exception-data-too-large-for-field-parentchild-id-cache/).

**Comment by clintongormley** [comment]
Also, indices created in 2.0 or later will store the parent_id as doc values not in-memory fielddata

**Comment by cawoodm** [comment]
Does it help in this case to split large indexes (e.g. by day myindex-yyyyMMdd) into separate indices?

**Comment by tdoman** [comment]
@ryancutter I wanted to read the document you referenced but it gives a PHP error: http://techieroop.com/circuitbreaking-exception-data-too-large-for-field-parentchild-id-cache/
Any other way to access that info?
