### ISSUE TITLE
Corrupted Shard Index After Upgrading 1.3.2 -> 1.4.2

### ISSUE THREAD

**Issue by GYatesIII** [elasticsearch/elasticsearch#9302]
I recently upgraded to 1.4.2 from 1.3.2 on a two node cluster. One shard cannot seem to make it back to one of the nodes. The log file complains of a corrupted index. I've restarted both servers and this doesn't seem to solve the issue.

The server that cannot get the shard is always consistent regardless if it's the master node or not, and it's always the same shard. The log file of the sending and receiving server are below:

**Receiving**
```
[2015-01-14 18:10:28,841][WARN ][cluster.action.shard     ] [Wild Child] [cerebro_concat][6] received shard failed for [cerebro_concat][6], node[pBHwfpf5Q7WFGLXrMo9Rhw], [R], s[INITIALIZING], indexUUID [OWZl5E21RQSUF9xOKk5tjw], reason [Failed to start shard, message [CorruptIndexException[[cerebro_concat][6] Preexisting corrupted index [corrupted_LT-2ZkELROmvz9YZZSmYHQ] caused by: CorruptIndexException[codec footer mismatch: actual footer=106421 vs expected footer=-1071082520 (resource: MMapIndexInput(path="/var/lib/elasticsearch/cerebroCrowdskout/nodes/0/indices/cerebro_concat/6/index/_d_es090_0.tim"))]
org.apache.lucene.index.CorruptIndexException: codec footer mismatch: actual footer=106421 vs expected footer=-1071082520 (resource: MMapIndexInput(path="/var/lib/elasticsearch/cerebroCrowdskout/nodes/0/indices/cerebro_concat/6/index/_d_es090_0.tim"))
	at org.apache.lucene.codecs.CodecUtil.validateFooter(CodecUtil.java:235)
	at org.apache.lucene.codecs.CodecUtil.retrieveChecksum(CodecUtil.java:228)
	at org.elasticsearch.index.store.Store$MetadataSnapshot.checksumFromLuceneFile(Store.java:686)
	at org.elasticsearch.index.store.Store$MetadataSnapshot.buildMetadata(Store.java:585)
	at org.elasticsearch.index.store.Store$MetadataSnapshot.<init>(Store.java:568)
	at org.elasticsearch.index.store.Store.getMetadata(Store.java:186)
	at org.elasticsearch.index.store.Store.getMetadataOrEmpty(Store.java:150)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyInitializingShard(IndicesClusterStateService.java:727)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyNewOrUpdatedShards(IndicesClusterStateService.java:579)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.clusterChanged(IndicesClusterStateService.java:185)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:431)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:153)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
]]]
```

**Sending**
```
[2015-01-14 18:10:28,841][WARN ][cluster.action.shard     ] [Airstrike] [cerebro_concat][6] sending failed shard for [cerebro_concat][6], node[pBHwfpf5Q7WFGLXrMo9Rhw], [R], s[INITIALIZING], indexUUID [OWZl5E21RQSUF9xOKk5tjw], reason [engine failure, message [corrupted preexisting index][CorruptIndexException[[cerebro_concat][6] Preexisting corrupted index [corrupted_LT-2ZkELROmvz9YZZSmYHQ] caused by: CorruptIndexException[codec footer mismatch: actual footer=106421 vs expected footer=-1071082520 (resource: MMapIndexInput(path="/var/lib/elasticsearch/cerebroCrowdskout/nodes/0/indices/cerebro_concat/6/index/_d_es090_0.tim"))]
org.apache.lucene.index.CorruptIndexException: codec footer mismatch: actual footer=106421 vs expected footer=-1071082520 (resource: MMapIndexInput(path="/var/lib/elasticsearch/cerebroCrowdskout/nodes/0/indices/cerebro_concat/6/index/_d_es090_0.tim"))
	at org.apache.lucene.codecs.CodecUtil.validateFooter(CodecUtil.java:235)
	at org.apache.lucene.codecs.CodecUtil.retrieveChecksum(CodecUtil.java:228)
	at org.elasticsearch.index.store.Store$MetadataSnapshot.checksumFromLuceneFile(Store.java:686)
	at org.elasticsearch.index.store.Store$MetadataSnapshot.buildMetadata(Store.java:585)
	at org.elasticsearch.index.store.Store$MetadataSnapshot.<init>(Store.java:568)
	at org.elasticsearch.index.store.Store.getMetadata(Store.java:186)
	at org.elasticsearch.index.store.Store.getMetadataOrEmpty(Store.java:150)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyInitializingShard(IndicesClusterStateService.java:727)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyNewOrUpdatedShards(IndicesClusterStateService.java:579)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.clusterChanged(IndicesClusterStateService.java:185)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:431)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:153)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
]]]
[2015-01-14 18:15:00,045][WARN ][index.engine.internal    ] [Airstrike] [cerebro_concat][6] failed engine [corrupted preexisting index]
org.apache.lucene.index.CorruptIndexException: [cerebro_concat][6] Preexisting corrupted index [corrupted_LT-2ZkELROmvz9YZZSmYHQ] caused by: CorruptIndexException[codec footer mismatch: actual footer=106421 vs expected footer=-1071082520 (resource: MMapIndexInput(path="/var/lib/elasticsearch/cerebroCrowdskout/nodes/0/indices/cerebro_concat/6/index/_d_es090_0.tim"))]
org.apache.lucene.index.CorruptIndexException: codec footer mismatch: actual footer=106421 vs expected footer=-1071082520 (resource: MMapIndexInput(path="/var/lib/elasticsearch/cerebroCrowdskout/nodes/0/indices/cerebro_concat/6/index/_d_es090_0.tim"))
	at org.apache.lucene.codecs.CodecUtil.validateFooter(CodecUtil.java:235)
	at org.apache.lucene.codecs.CodecUtil.retrieveChecksum(CodecUtil.java:228)
	at org.elasticsearch.index.store.Store$MetadataSnapshot.checksumFromLuceneFile(Store.java:686)
	at org.elasticsearch.index.store.Store$MetadataSnapshot.buildMetadata(Store.java:585)
	at org.elasticsearch.index.store.Store$MetadataSnapshot.<init>(Store.java:568)
	at org.elasticsearch.index.store.Store.getMetadata(Store.java:186)
	at org.elasticsearch.index.store.Store.getMetadataOrEmpty(Store.java:150)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyInitializingShard(IndicesClusterStateService.java:727)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyNewOrUpdatedShards(IndicesClusterStateService.java:579)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.clusterChanged(IndicesClusterStateService.java:185)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:431)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:153)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

	at org.elasticsearch.index.store.Store.failIfCorrupted(Store.java:452)
	at org.elasticsearch.index.store.Store.failIfCorrupted(Store.java:433)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyInitializingShard(IndicesClusterStateService.java:726)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyNewOrUpdatedShards(IndicesClusterStateService.java:579)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.clusterChanged(IndicesClusterStateService.java:185)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:431)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:153)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2015-01-14 18:15:00,046][WARN ][indices.cluster          ] [Airstrike] [cerebro_concat][6] failed to start shard
org.apache.lucene.index.CorruptIndexException: [cerebro_concat][6] Preexisting corrupted index [corrupted_LT-2ZkELROmvz9YZZSmYHQ] caused by: CorruptIndexException[codec footer mismatch: actual footer=106421 vs expected footer=-1071082520 (resource: MMapIndexInput(path="/var/lib/elasticsearch/cerebroCrowdskout/nodes/0/indices/cerebro_concat/6/index/_d_es090_0.tim"))]
org.apache.lucene.index.CorruptIndexException: codec footer mismatch: actual footer=106421 vs expected footer=-1071082520 (resource: MMapIndexInput(path="/var/lib/elasticsearch/cerebroCrowdskout/nodes/0/indices/cerebro_concat/6/index/_d_es090_0.tim"))
	at org.apache.lucene.codecs.CodecUtil.validateFooter(CodecUtil.java:235)
	at org.apache.lucene.codecs.CodecUtil.retrieveChecksum(CodecUtil.java:228)
	at org.elasticsearch.index.store.Store$MetadataSnapshot.checksumFromLuceneFile(Store.java:686)
	at org.elasticsearch.index.store.Store$MetadataSnapshot.buildMetadata(Store.java:585)
	at org.elasticsearch.index.store.Store$MetadataSnapshot.<init>(Store.java:568)
	at org.elasticsearch.index.store.Store.getMetadata(Store.java:186)
	at org.elasticsearch.index.store.Store.getMetadataOrEmpty(Store.java:150)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyInitializingShard(IndicesClusterStateService.java:727)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyNewOrUpdatedShards(IndicesClusterStateService.java:579)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.clusterChanged(IndicesClusterStateService.java:185)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:431)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:153)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

	at org.elasticsearch.index.store.Store.failIfCorrupted(Store.java:452)
	at org.elasticsearch.index.store.Store.failIfCorrupted(Store.java:433)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyInitializingShard(IndicesClusterStateService.java:726)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyNewOrUpdatedShards(IndicesClusterStateService.java:579)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.clusterChanged(IndicesClusterStateService.java:185)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:431)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:153)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

Thank you for your help, and please let me know if I can provide further information to help with debugging.

**Comment by clintongormley** [comment]
Hi @GYatesIII 

It looks like your replica shard is corrupt - it is smaller than it should be.  I think you should be able to delete the directory containing that shard (`/var/lib/elasticsearch/cerebroCrowdskout/nodes/0/indices/cerebro_concat/6` on that node) and it should recover from the primary.

**Comment by GYatesIII** [comment]
Yup, that fixed the issue, thanks.

Any idea what may have caused the corruption?

**Comment by clintongormley** [comment]
Glad to hear it.  It looks like a file was truncated while recovering the replica from the primary, on an older version.  We've added a lot more checksumming since then, and safer recovery, so hopefully you shouldn't see this again.
