### ISSUE TITLE
request queue blocked forever (again)

### ISSUE THREAD

**Issue by Jens-G** [elasticsearch/elasticsearch#9390]
I got a very similar problem as described in #4887. But I run 1.4.2 and the behaviour is still very reliable reproducible on my test machine here. I just try to feed a lot of small entries via logstash into ES and get a similar message and the net effect of a hanging, overloaded queue. 

I might add that said test machine is a bit low resourced, just in case it plays a role here. The ES setup I use is basically "factory default".

```
[2015-01-23 02:25:41,572][DEBUG][action.search.type       ] [Agamemnon] [logstash-1990.10.17][2], node[hUACqH-ETmabS0aMAwVi4g], [P], s[STARTED]: Failed to execu
te [org.elasticsearch.action.search.SearchRequest@4e76a9] lastShard [true]
org.elasticsearch.common.util.concurrent.EsRejectedExecutionException: rejected execution (queue capacity 1000) on org.elasticsearch.search.action.SearchService
TransportAction$23@19362f0
        at org.elasticsearch.common.util.concurrent.EsAbortPolicy.rejectedExecution(EsAbortPolicy.java:62)
        at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.execute(Unknown Source)
        at org.elasticsearch.search.action.SearchServiceTransportAction.execute(SearchServiceTransportAction.java:551)
        at org.elasticsearch.search.action.SearchServiceTransportAction.sendExecuteQuery(SearchServiceTransportAction.java:228)
        at org.elasticsearch.action.search.type.TransportSearchQueryThenFetchAction$AsyncAction.sendExecuteFirstPhase(TransportSearchQueryThenFetchAction.java:8
2)
        at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction.performFirstPhase(TransportSearchTypeAction.java:171)
        at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction.start(TransportSearchTypeAction.java:153)
        at org.elasticsearch.action.search.type.TransportSearchQueryThenFetchAction.doExecute(TransportSearchQueryThenFetchAction.java:61)
        at org.elasticsearch.action.search.type.TransportSearchQueryThenFetchAction.doExecute(TransportSearchQueryThenFetchAction.java:51)
        at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:75)
        at org.elasticsearch.action.search.TransportSearchAction.doExecute(TransportSearchAction.java:103)
        at org.elasticsearch.action.search.TransportSearchAction.doExecute(TransportSearchAction.java:45)
        at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:75)
        at org.elasticsearch.client.node.NodeClient.execute(NodeClient.java:98)
        at org.elasticsearch.client.FilterClient.execute(FilterClient.java:66)
        at org.elasticsearch.rest.BaseRestHandler$HeadersAndContextCopyClient.execute(BaseRestHandler.java:92)
        at org.elasticsearch.client.support.AbstractClient.search(AbstractClient.java:334)
        at org.elasticsearch.rest.action.search.RestSearchAction.handleRequest(RestSearchAction.java:81)
        at org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:53)
        at org.elasticsearch.rest.RestController.executeHandler(RestController.java:197)
        at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:180)
        at org.elasticsearch.http.HttpServer.internalDispatchRequest(HttpServer.java:121)
        at org.elasticsearch.http.HttpServer$Dispatcher.dispatchRequest(HttpServer.java:83)
        at org.elasticsearch.http.netty.NettyHttpServerTransport.dispatchRequest(NettyHttpServerTransport.java:319)
        at org.elasticsearch.http.netty.HttpRequestHandler.messageReceived(HttpRequestHandler.java:61)
        at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.elasticsearch.http.netty.pipelining.HttpPipeliningHandler.messageReceived(HttpPipeliningHandler.java:60)
        at org.elasticsearch.common.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.elasticsearch.common.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:145)
        at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.elasticsearch.common.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:108)
        at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:296)
        at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
        at org.elasticsearch.common.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
        at org.elasticsearch.common.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
        at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:74)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
        at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:268)
        at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:255)
        at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

When I stop the thing, it prints a huge pile of the messages below right before exiting:

```
[2015-01-23 02:46:14,559][DEBUG][action.bulk              ] [Agamemnon] observer timed out. notifying listener. timeout setting [1m], time since start [26m]
[2015-01-23 02:46:14,590][DEBUG][action.bulk              ] [Agamemnon] observer timed out. notifying listener. timeout setting [1m], time since start [26m]
[2015-01-23 02:46:14,621][DEBUG][action.bulk              ] [Agamemnon] observer timed out. notifying listener. timeout setting [1m], time since start [26m]
[2015-01-23 02:46:14,653][DEBUG][action.bulk              ] [Agamemnon] observer timed out. notifying listener. timeout setting [1m], time since start [26m]
[2015-01-23 02:46:14,653][DEBUG][action.bulk              ] [Agamemnon] observer timed out. notifying listener. timeout setting [1m], time since start [26m]
[2015-01-23 02:46:14,574][DEBUG][action.bulk              ] [Agamemnon] observer timed out. notifying listener. timeout setting [1m], time since start [26m]
[2015-01-23 02:46:14,653][DEBUG][action.bulk              ] [Agamemnon] observer timed out. notifying listener. timeout setting [1m], time since start [26m]
[2015-01-23 02:46:14,637][INFO ][node                     ] [Agamemnon] stopped
```

**Comment by Jens-G** [comment]
Another remark: The "hang" does not refer to a specific call I made, Rather I see only a few entries being processed: I get something around 70 (!) newly added entries processed so I can query them. I had expected at least something around 1000, if that's the max queue size. But even after waiting > 20 minutes, which is very long for these small data pieces, I still have only the 70 entries. The full input would be something around 5300 messages.

**Comment by Jens-G** [comment]
I throttled the Input and it still takes forever. It looks as if ES has problems with lots of indices. The more indices I have, the slower it becomes (LogStash creates one index per day, I have around 5300 of them). The JavaVM puts a constant load around 75% on the CPU but nothing happens.

**Comment by Jens-G** [comment]
I modified the data that go into ES to minimize index creation and it works like a charm, performant and all. So the question raises, whether this could that be related to memory or other per-index resources somehow? I'm on a Windows platform.

**Comment by clintongormley** [comment]
Hi @Jens-G 

It sounds like you are overloading a poorly configured Elasticsearch instance.  You say you're pretty much using factory defaults.  Quite possibly you haven't configured ES_HEAP_SIZE? Or mlockall (although with windows you'll probably need to disable the page file instead)? If not, then it is quite likely you're seeing slow garbage collections. Perhaps the file handle limit need attention too?

It also sounds like you're not checking the responses from bulk requests, or waiting for them to complete. You're just piling as much as you can into the node as fast as possible?

You say you have 5,300 indices, presumably with 5 shards each, so 25k shards (or is there more than one node, so you have replicas assigned giving you 50k shards), all on a box with poor resources.  To help explain why this is a bad idea, read this: http://www.elasticsearch.org/guide/en/elasticsearch/guide/current/finite-scale.html#finite-scale

**Comment by Jens-G** [comment]
Thanks for the feedback and (especially) the link, I think you're right. I almost guessed it.

**Comment by clintongormley** [comment]
great - closing this then
