### ISSUE TITLE
Parse Failure [No mapping found for [@timestamp] in order to sort on]

### ISSUE THREAD

**Issue by versnel** [elasticsearch/elasticsearch#9405]
Hallo there,

I'm getting the following Error msg in my log file.
Can someone help me to solve this.
Thank you

Extra info:
Elasticsearch: 1.4.2
Logstash: 1.4.2-1
Kibana: 3.1.2

[2015-01-25 17:08:54,685][DEBUG][action.search.type       ] [suricata] [kibana-int][1], node[vgiCpnXoS-GTnJBZhd9E5g], [P], s[STARTED]: Failed to execute [org.elasticsearch.action.search.SearchRequest@2b88da4e] lastShard [true]
org.elasticsearch.transport.RemoteTransportException: [Terraxia][inet[/PUBLIC_IP:9304]][search/phase/query]
Caused by: org.elasticsearch.search.SearchParseException: [kibana-int][1]: query[MatchNoDocsQuery],from[-1],size[100000]: Parse Failure [Failed to parse source [{"query":{"filtered":{"query":{"bool":{}},"filter":{"bool":{"must":[{"range":{"@timestamp":{"from":1422119331438,"to":1422205731438}}},{"exists":{"field":"geoip.coordinates"}}]}}}},"fields":["geoip.coordinates","_id"],"size":100000,"sort":[{"@timestamp":{"order":"desc"}}]}]]
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:634)
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:507)
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:480)
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:252)
        at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:623)
        at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:612)
        at org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler.run(MessageChannelHandler.java:270)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.search.SearchParseException: [kibana-int][1]: query[MatchNoDocsQuery],from[-1],size[100000]: Parse Failure [No mapping found for [@timestamp] in order to sort on]
        at org.elasticsearch.search.sort.SortParseElement.addSortField(SortParseElement.java:198)
        at org.elasticsearch.search.sort.SortParseElement.addCompoundSortField(SortParseElement.java:172)
        at org.elasticsearch.search.sort.SortParseElement.parse(SortParseElement.java:80)
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:622)

**Comment by clintongormley** [comment]
Hi @versnel 

Please ask questions like these in the user forums.  The github issues list is for bug reports and feature requests.  Very simply: you're trying to sort documents that don't have a @timestamp field declared in their index/type.
