### ISSUE TITLE
Unable to read disk usage on CloudLinux

### ISSUE THREAD

**Issue by isodude** [elasticsearch/elasticsearch#9482]
Hi,

Trying to run ElasticSearch within a CloudLinux Cage (Jails on RedHat), but it isn't possible to know how much disk is free since it's not possible to read mount-points at all. (i.e. df doesn't work)

Running on ElasticSearch 1.4.2 and java-1.8.0-openjdk on Centos 6.5 with latest CloudLinux:

[2015-01-29 12:53:57,578][DEBUG][action.admin.cluster.node.stats] [Mark Gervaisnight Shade] failed to execute on node [HPho5ursQjqsiQqcR2Arig]
java.lang.IllegalStateException: Free bytes [-1] cannot be less than 0 or greater than total bytes [-1]
	at org.elasticsearch.cluster.DiskUsage.<init>(DiskUsage.java:36)
	at org.elasticsearch.cluster.InternalClusterInfoService$ClusterInfoUpdateJob$1.onResponse(InternalClusterInfoService.java:311)
	at org.elasticsearch.cluster.InternalClusterInfoService$ClusterInfoUpdateJob$1.onResponse(InternalClusterInfoService.java:291)
	at org.elasticsearch.action.LatchedActionListener.onResponse(LatchedActionListener.java:41)
	at org.elasticsearch.action.support.nodes.TransportNodesOperationAction$AsyncAction.finishHim(TransportNodesOperationAction.java:222)
	at org.elasticsearch.action.support.nodes.TransportNodesOperationAction$AsyncAction.onOperation(TransportNodesOperationAction.java:197)
	at org.elasticsearch.action.support.nodes.TransportNodesOperationAction$AsyncAction.access$900(TransportNodesOperationAction.java:97)
	at org.elasticsearch.action.support.nodes.TransportNodesOperationAction$AsyncAction$2.run(TransportNodesOperationAction.java:141)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

There's a new throw inside the diskspace-code that producing this (https://github.com/elasticsearch/elasticsearch/blob/v1.4.2/src/main/java/org/elasticsearch/cluster/DiskUsage.java:36).

Anyway around it?

**Comment by isodude** [comment]
It seems to work when running elasticsearch 0.90.13, at least it doesn't stacktrace. But it will perhaps crasch at another point.

**Comment by dakrone** [comment]
This was fixed in #9283, as a workaround in the meantime, if you are not using the disk-based shard allocation you can disable this by setting `cluster.routing.allocation.disk.threshold_enabled` to `false` and the disk usages will not be checked.
