### ISSUE TITLE
java.lang.NullPointerException when using embedded Node client + marvel when stopped

### ISSUE THREAD

**Issue by ppearcy** [elasticsearch/elasticsearch#9601]
This is on 1.4.1 and I only hit it when tests complete and cleanup, so pretty low priority. Here is the stack trace:

    Exception encountered when invoking run on a nested suite.
    java.lang.NullPointerException
        at org.elasticsearch.marvel.agent.exporter.ESExporter.doStop(ESExporter.java:272)
        at org.elasticsearch.common.component.AbstractLifecycleComponent.stop(AbstractLifecycleComponent.java:105)   
        at org.elasticsearch.marvel.agent.AgentService.doStop(AgentService.java:186)   
        at org.elasticsearch.common.component.AbstractLifecycleComponent.stop(AbstractLifecycleComponent.java:105)
        at org.elasticsearch.node.internal.InternalNode.stop(InternalNode.java:307)

**Comment by bleskes** [comment]
@ppearcy double checking, with which version of Marvel this is happening?

**Comment by ppearcy** [comment]
Ah, it was happening in 1.2.1. I just update to 1.3.0 and no longer occurs, sorry for the noise and thanks!

**Comment by bleskes** [comment]
No worries.  Th. For reporting.
