### ISSUE TITLE
Elasticsearch translog corruption if process is killed

### ISSUE THREAD

**Issue by athanikkal** [elasticsearch/elasticsearch#9699]
We found that Elasticsearch transaction log gets corrupted occasionally if the process is killed abruptly by any reason including power shutdown while indexing is going on. As the default translog flush interval is 5 seconds, we expect to loose transactions for the past 5 seconds not translog corruption in this case. This can be easily reproduced by invoking kill -9 on elasticsearch process repeatedly and restarting while sending index requests continuously.  I have attached 2 linux shell scripts to kill and restart ES.

#### Extract from log:

[2015-02-14 00:00:53,965][WARN ][indices.cluster          ] [r1s8-1.dg.com] [curr_1024][3] failed to start shard
org.elasticsearch.index.gateway.IndexShardGatewayRecoveryException: [curr_1024][3] failed to recover shard
        at org.elasticsearch.index.gateway.local.LocalIndexShardGateway.recover(LocalIndexShardGateway.java:287)
        at org.elasticsearch.index.gateway.IndexShardGatewayService$1.run(IndexShardGatewayService.java:132)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)
Caused by: org.elasticsearch.index.translog.TranslogCorruptedException: translog corruption while reading from stream
        at org.elasticsearch.index.translog.ChecksummedTranslogStream.read(ChecksummedTranslogStream.java:70)
        at org.elasticsearch.index.gateway.local.LocalIndexShardGateway.recover(LocalIndexShardGateway.java:257)
        ... 4 more
Caused by: java.io.EOFException
        at org.elasticsearch.common.io.stream.InputStreamStreamInput.readByte(InputStreamStreamInput.java:43)
        at org.elasticsearch.index.translog.BufferedChecksumStreamInput.readByte(BufferedChecksumStreamInput.java:48)
        at org.elasticsearch.common.io.stream.StreamInput.readInt(StreamInput.java:116)
        at org.elasticsearch.common.io.stream.StreamInput.readLong(StreamInput.java:156)
        at org.elasticsearch.index.translog.Translog$Create.readFrom(Translog.java:371)
        at org.elasticsearch.index.translog.ChecksummedTranslogStream.read(ChecksummedTranslogStream.java:68)
        ... 5 more
[2015-02-14 00:00:53,979][WARN ][cluster.action.shard     ] [r1s8-1.dg.com] [curr_1024][3] sending failed shard for [curr_1024][3], node[9Ip4LaEbTnqVa8xOtVocHg], [P], s[INITIALIZING], indexUUID [F1efdIdUQwONYbyYMqloEg], reason [Failed to start shard, message [IndexShardGatewayRecoveryException[[curr_1024][3] failed to recover shard]; nested: TranslogCorruptedException[translog corruption while reading from stream]; nested: EOFException; ]]
[2015-02-14 00:00:53,980][WARN ][cluster.action.shard     ] [r1s8-1.dg.com] [curr_1024][3] received shard failed for [curr_1024][3], node[9Ip4LaEbTnqVa8xOtVocHg], [P], s[INITIALIZING], indexUUID [F1efdIdUQwONYbyYMqloEg], reason [Failed to start shard, message [IndexShardGatewayRecoveryException[[curr_1024][3] failed to recover shard]; nested: TranslogCorruptedException[translog corruption while reading from stream]; nested: EOFException; ]]

````
/********************************************************/
killes.sh script
/**********************************************************/
#!/bin/sh
#this script will kill ES periodically

if [ -z "$1" ]
then
    echo "Usage: $0 <sleepinterval>"
    exit 1
fi

while [ : ]
do
    pid=`ps aux | grep  elastic | grep -v "grep" | awk '{print $2}'`
    if [ ! -z "${pid}" ]
    then
            echo "killing es process $pid"
            kill -9 ${pid}
    fi
    sleep $1
done

/*******************************************************************/
restart_es shell script
/*******************************************************************/

#!/bin/bash
#This script is used to restart ES on failure

ES_ROOT=/var/ES
export ES_HEAP_SIZE=12g  # real size, for scale and performance testing
ES_HOME=/opt/elasticsearch
export ES_DIRECT_SIZE=1024m
export ES_JAVA_OPTS="-XX:HeapDumpPath=$ES_ROOT/cores/esheapdump.hprof"

while true; do
    #start ES server in foreground
    mkdir -p $ES_ROOT/log/
    ulimit -n 65534;$ES_HOME/bin/elasticsearch -Des.node.name="`hostname`"  2>&1 | logger -t es_mon
    echo "ES server exit with code $? , waiting to restart..." | logger -t dg_es_mon
    sleep 2  #pause before restart so ES processes can be cleaned up
done
````

**Comment by mkliu** [comment]
+1 happend on windows too. Anyway to mitigate this?

**Comment by jamilbk** [comment]
+1 on Mac OS X here. Had to hard reset my Macbook and now getting translog corruption issues. Pegged about 100% of two CPU cores for a ~ 3.3 GB index. No other indexes.

**Comment by marksheinbaum** [comment]
we are seeing something similar after running into "no more space available" on local disk. Not clear if this has been fixed, or is in flight. We are running ES version 1.4.0 with lucene version 4.10.2. Any info is appreciated. Thanks.

**Comment by choweiyuan** [comment]
This happened for me with 1.4.1, will this be fixed in 1.4.x?

**Comment by dakrone** [comment]
@choweiyuan yes, I am planning on backporting this to the 1.4 branch

**Comment by choweiyuan** [comment]
Thanks @dakrone !

**Comment by athanikkal** [comment]
Thanks @dakrone for fixing this promptly. Looking forward to the next 1.4.x release with this fix.

**Comment by balaji006** [comment]
Delete .recovery file inside the translog folder

Eg:/es/elasticsearch-1.7.1/data/[elasticsearch_clustername]/nodes/0/indices/[indexname]/2/translog/

**Comment by ramo85** [comment]
Am 01.09.2015 16:49 schrieb "balaji006" <notifications@github.com>:

**Comment by ramo85** [comment]
https://www.google.de/chrome/browser/desktop/


<https://ssl.gstatic.com/docs/doclist/images/icon_11_image_list.png>   My
Data Manager Service

**Comment by ramo85** [comment]
Am 01.09.2015 16:49 schrieb "balaji006" <notifications@github.com>:
>
> Delete .recovery file inside the translog folder
>
>
Eg:/es/elasticsearch-1.7.1/data/[elasticsearch_clustername]/nodes/0/indices/[indexname]/2/translog/

**Comment by marksheinbaum** [comment]
stop

**Comment by ramo85** [comment]
https://console.developers.google.com/storage/browser/takeout-eu/20150818T055549Z/1108462567876711962/bd597f69-ec64-49da-97ff-a9269715e12c/1/23e2771e-f7f1-4831-b1e4-f64944c31501/

Von Samsung Mobile gesendet

**Comment by ramo85** [comment]
Hey,

ich habe gerade WhatsApp auf mein Android heruntergeladen.

Das ist eine Smartphone Messaging App, mit der ich ohne SMS direkt mit meinen Freunden und Kontakten chatten kann. Die App kann Bilder, Videos und andere Multimedia-Daten senden.

WhatsApp ist für Android, iPhone, Windows Phone, BlackBerry und Nokia erhältlich. Man muss sich keine PIN oder Benutzernamen merken - es funktioniert wie SMS, aber verwendet deinen Datentarif.

Die App ist unter https://www.whatsapp.com/download/ erhältlich.

Von Samsung Mobile gesendet

**Comment by ambodi** [comment]
can you guys fix this? I am still seeing this in 1.7.3 and it's not nice really.

**Comment by clintongormley** [comment]
@ambodi the translog underwent a huge rewrite in 2.x and it can't be backported.  time to upgrade

**Comment by ambodi** [comment]
@clintongormley oh man! Okay, thanks! 👍 👍
