### ISSUE TITLE
Marvel 1.3.0 on ES 1.4.3 requires http.enabled

### ISSUE THREAD

**Issue by JakeFromTheDark** [elasticsearch/elasticsearch#9758]
Marvel 1.3.0 on ES 1.4.3 requires `http.enabled: true` **on every node** - even there where HTTP module is not needed (master and data nodes). Else the node will fail with `No implementation for org.elasticsearch.http.HttpServerTransport was bound`.

**`elasticsearch.yml`**:
````
### MANAGED BY PUPPET ###
---
cluster: 
  name: ES-on-vagrant.dev
discovery: 
  zen: 
    ping: 
      multicast: 
        enabled: false
      unicast: 
        hosts: 
             - es02m.vagrant.dev:9300
http: 
  cors: 
    enabled: true
  enabled: false
index: 
  number_of_replicas: 0
  number_of_shards: 5
marvel: 
  agent: 
    exporter: 
      es: 
        hosts: 
             - es21s.vagrant.dev:9200
network: 
  bind_host: 0.0.0.0
  publish_host: _eth1:ipv4_
node: 
  data: true
  master: false
  name: es11d-es-01
path: 
  data: /usr/share/elasticsearch/data/es-01
````

Debug log:
````
[2015-02-19 10:40:37,433][INFO ][node                     ] [es11d-es-01] version[1.4.3], pid[3637], build[36a29a7/2015-02-11T14:23:15Z]
[2015-02-19 10:40:37,435][INFO ][node                     ] [es11d-es-01] initializing ...
[2015-02-19 10:40:37,435][DEBUG][node                     ] [es11d-es-01] using home [/usr/share/elasticsearch], config [/etc/elasticsearch/es-01], data [[/usr/share/elasticsearch/data/es-01]], logs [/var/log/elasticsearch/es-01], 
work [/usr/share/elasticsearch/work], plugins [/usr/share/elasticsearch/plugins]
[2015-02-19 10:40:37,442][DEBUG][plugins                  ] [es11d-es-01] lucene property is not set in plugin es-plugin.properties file. Skipping test.
[2015-02-19 10:40:37,445][INFO ][plugins                  ] [es11d-es-01] loaded [marvel], sites [marvel]
[2015-02-19 10:40:37,463][DEBUG][common.compress.lzf      ] using encoder [VanillaChunkDecoder] and decoder[{}] 
[2015-02-19 10:40:37,472][DEBUG][env                      ] [es11d-es-01] using node location [[/usr/share/elasticsearch/data/es-01/ES-on-vagrant.dev/nodes/0]], local_node_id [0]
[2015-02-19 10:40:38,788][ERROR][bootstrap                ] {1.4.3}: Initialization Failed ...
1) No implementation for org.elasticsearch.http.HttpServerTransport was bound.
org.elasticsearch.common.inject.CreationException: Guice creation errors:

1) No implementation for org.elasticsearch.http.HttpServerTransport was bound.
  while locating org.elasticsearch.http.HttpServerTransport
    for parameter 2 at org.elasticsearch.http.HttpServer.<init>(Unknown Source)
  while locating org.elasticsearch.http.HttpServer
    for parameter 0 at org.elasticsearch.marvel.agent.exporter.ESExporter.setHttpServer(Unknown Source)
  at org.elasticsearch.marvel.agent.exporter.ESExporter.setHttpServer(Unknown Source)
  at org.elasticsearch.marvel.agent.AgentModule.configure(AgentModule.java:31)

1 error
	at org.elasticsearch.common.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:344)
	at org.elasticsearch.common.inject.InjectorBuilder.initializeStatically(InjectorBuilder.java:151)
	at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:102)
	at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:93)
	at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:70)
	at org.elasticsearch.common.inject.ModulesBuilder.createInjector(ModulesBuilder.java:59)
	at org.elasticsearch.node.internal.InternalNode.<init>(InternalNode.java:197)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:159)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:70)
	at org.elasticsearch.bootstrap.Bootstrap.main(Bootstrap.java:203)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:32)

[2015-02-19 10:40:38,789][DEBUG][bootstrap                ] Exception
org.elasticsearch.common.inject.CreationException: Guice creation errors:

1) No implementation for org.elasticsearch.http.HttpServerTransport was bound.
  while locating org.elasticsearch.http.HttpServerTransport
    for parameter 2 at org.elasticsearch.http.HttpServer.<init>(Unknown Source)
  while locating org.elasticsearch.http.HttpServer
    for parameter 0 at org.elasticsearch.marvel.agent.exporter.ESExporter.setHttpServer(Unknown Source)
  at org.elasticsearch.marvel.agent.exporter.ESExporter.setHttpServer(Unknown Source)
  at org.elasticsearch.marvel.agent.AgentModule.configure(AgentModule.java:31)

1 error
	at org.elasticsearch.common.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:344)
	at org.elasticsearch.common.inject.InjectorBuilder.initializeStatically(InjectorBuilder.java:151)
	at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:102)
	at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:93)
	at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:70)
	at org.elasticsearch.common.inject.ModulesBuilder.createInjector(ModulesBuilder.java:59)
	at org.elasticsearch.node.internal.InternalNode.<init>(InternalNode.java:197)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:159)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:70)
	at org.elasticsearch.bootstrap.Bootstrap.main(Bootstrap.java:203)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:32)
````

**Comment by bleskes** [comment]
Yeah. We're working on a fix. Thank you for reporting.

**Comment by AlexClineBB** [comment]
I've encountered this problem on 1.4.4 as well.

**Comment by bleskes** [comment]
Yes. This is an issue with marvel, not Elasticsearch.

**Comment by maaand** [comment]
Is there a work-around for this? -- other than running http client on all nodes

**Comment by bleskes** [comment]
hi all. A short note to say this issue is fixed with Marvel 1.3.1 released today. I'm going to close this. Please let me know if something doesn't work as you expect.

**Comment by maaand** [comment]
@bleskes can you point me to the configuration doc for Marvel-1.3.1 ?
I've upgraded marvel plugin and  set http.enabled = false  (on my ES datanode) 
and now my es log is filling up with warning.. 
[2015-03-05 14:27:09,336][WARN ][marvel.agent.exporter    ] [xxxx_search_cluster] http server is not enabled no hosts are manually configured

**Comment by bleskes** [comment]
Marvel ships data over http. It can be configured using a list of host/ip + port, in the case you want to send the data to a dedicated monitoring cluster (recommended) or it defaults to shipping the local cluster. This error message indicates that no hosts explicitly configured (first use case) and that the local http server is turned off, so data can not be shipped there either. If you want to store the marvel data on the local cluster, you will have to enable http. You could bind it to local host and ship there.

**Comment by eddygithub** [comment]
I am using elasticsearch 1.5 and marvel 1.3.1.  I am getting the following errors when I tried to start TransportClient.  It works fine when I removed marvel.

	Properties props = new Properties();
			props.put(ESCliAdminCommands.CLUSTER_NAME_OPTION, clusterName);
			props.put(ESCliAdminCommands.NODE_NAME_OPTION, nodeName);
			props.put("client.transport.sniff", "true");
			Settings settings = ImmutableSettings.settingsBuilder().put(props).build();
			client = new TransportClient(settings).addTransportAddress(new InetSocketTransportAddress(hostName, port));


org.elasticsearch.common.inject.CreationException: Guice creation errors:

1) No implementation for org.elasticsearch.client.Client was bound.
  while locating org.elasticsearch.client.Client
    for parameter 4 at org.elasticsearch.marvel.agent.AgentService.<init>(Unknown Source)
  at _unknown_

2) No implementation for org.elasticsearch.cluster.ClusterService was bound.
  while locating org.elasticsearch.cluster.ClusterService
    for parameter 3 at org.elasticsearch.marvel.agent.AgentService.<init>(Unknown Source)
  at _unknown_

3) No implementation for org.elasticsearch.cluster.ClusterService was bound.
  while locating org.elasticsearch.cluster.ClusterService
    for parameter 1 at org.elasticsearch.marvel.agent.exporter.ESExporter.<init>(Unknown Source)
  at _unknown_

4) No implementation for org.elasticsearch.cluster.settings.DynamicSettings annotated with @org.elasticsearch.cluster.settings.ClusterDynamicSettings() was bound.
  while locating org.elasticsearch.cluster.settings.DynamicSettings annotated with @org.elasticsearch.cluster.settings.ClusterDynamicSettings()
    for parameter 7 at org.elasticsearch.marvel.agent.AgentService.<init>(Unknown Source)
  at _unknown_

5) No implementation for org.elasticsearch.cluster.settings.DynamicSettings annotated with @org.elasticsearch.cluster.settings.ClusterDynamicSettings() was bound.
  while locating org.elasticsearch.cluster.settings.DynamicSettings annotated with @org.elasticsearch.cluster.settings.ClusterDynamicSettings()
    for parameter 3 at org.elasticsearch.marvel.agent.exporter.ESExporter.<init>(Unknown Source)
  at _unknown_

6) No implementation for org.elasticsearch.discovery.Discovery was bound.
  while locating org.elasticsearch.discovery.Discovery
    for parameter 3 at org.elasticsearch.node.service.NodeService.<init>(Unknown Source)
  while locating org.elasticsearch.node.service.NodeService
    for parameter 2 at org.elasticsearch.marvel.agent.AgentService.<init>(Unknown Source)
  at _unknown_

7) No implementation for org.elasticsearch.indices.IndicesLifecycle was bound.
  while locating org.elasticsearch.indices.IndicesLifecycle
    for parameter 1 at org.elasticsearch.indices.IndicesService.<init>(Unknown Source)
  while locating org.elasticsearch.indices.IndicesService
    for parameter 5 at org.elasticsearch.node.service.NodeService.<init>(Unknown Source)
  while locating org.elasticsearch.node.service.NodeService
    for parameter 2 at org.elasticsearch.marvel.agent.AgentService.<init>(Unknown Source)
  at _unknown_

8) No implementation for org.elasticsearch.indices.IndicesLifecycle was bound.
  while locating org.elasticsearch.indices.IndicesLifecycle
    for parameter 1 at org.elasticsearch.marvel.agent.AgentService.<init>(Unknown Source)
  at _unknown_

9) No implementation for org.elasticsearch.monitor.fs.FsProbe was bound.
  while locating org.elasticsearch.monitor.fs.FsProbe
    for parameter 1 at org.elasticsearch.monitor.fs.FsService.<init>(Unknown Source)
  while locating org.elasticsearch.monitor.fs.FsService
    for parameter 6 at org.elasticsearch.monitor.MonitorService.<init>(Unknown Source)
  while locating org.elasticsearch.monitor.MonitorService
    for parameter 2 at org.elasticsearch.node.service.NodeService.<init>(Unknown Source)
  while locating org.elasticsearch.node.service.NodeService
    for parameter 2 at org.elasticsearch.marvel.agent.AgentService.<init>(Unknown Source)
  at _unknown_

10) No implementation for org.elasticsearch.monitor.network.NetworkProbe was bound.
  while locating org.elasticsearch.monitor.network.NetworkProbe
    for parameter 1 at org.elasticsearch.monitor.network.NetworkService.<init>(Unknown Source)
  while locating org.elasticsearch.monitor.network.NetworkService
    for parameter 5 at org.elasticsearch.monitor.MonitorService.<init>(Unknown Source)
  while locating org.elasticsearch.monitor.MonitorService
    for parameter 2 at org.elasticsearch.node.service.NodeService.<init>(Unknown Source)
  while locating org.elasticsearch.node.service.NodeService
    for parameter 2 at org.elasticsearch.marvel.agent.AgentService.<init>(Unknown Source)
  at _unknown_

11) No implementation for org.elasticsearch.monitor.os.OsProbe was bound.
  while locating org.elasticsearch.monitor.os.OsProbe
    for parameter 1 at org.elasticsearch.monitor.os.OsService.<init>(Unknown Source)
  while locating org.elasticsearch.monitor.os.OsService
    for parameter 2 at org.elasticsearch.monitor.MonitorService.<init>(Unknown Source)
  while locating org.elasticsearch.monitor.MonitorService
    for parameter 2 at org.elasticsearch.node.service.NodeService.<init>(Unknown Source)
  while locating org.elasticsearch.node.service.NodeService
    for parameter 2 at org.elasticsearch.marvel.agent.AgentService.<init>(Unknown Source)
  at _unknown_

12) No implementation for org.elasticsearch.monitor.process.ProcessProbe was bound.
  while locating org.elasticsearch.monitor.process.ProcessProbe
    for parameter 1 at org.elasticsearch.monitor.process.ProcessService.<init>(Unknown Source)
  while locating org.elasticsearch.monitor.process.ProcessService
    for parameter 3 at org.elasticsearch.monitor.MonitorService.<init>(Unknown Source)
  while locating org.elasticsearch.monitor.MonitorService
    for parameter 2 at org.elasticsearch.node.service.NodeService.<init>(Unknown Source)
  while locating org.elasticsearch.node.service.NodeService
    for parameter 2 at org.elasticsearch.marvel.agent.AgentService.<init>(Unknown Source)
  at _unknown_

12 errors
	at org.elasticsearch.common.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:344)
	at org.elasticsearch.common.inject.InjectorBuilder.initializeStatically(InjectorBuilder.java:151)
	at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:102)
	at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:93)
	at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:70)
	at org.elasticsearch.common.inject.ModulesBuilder.createInjector(ModulesBuilder.java:59)
	at org.elasticsearch.client.transport.TransportClient.<init>(TransportClient.java:187)
	at org.elasticsearch.client.transport.TransportClient.<init>(TransportClient.java:123)

**Comment by bleskes** [comment]
@eddygithub I'm not sure exactly what you are doing but it feels like you have are starting a transport client from your application and have marvel in the class path. Marvel hooks into the ES nodes and requires more than what the TransportClient has to offer (hence the errors). Unless you have a good reason to have Marvel around, I would just remove it from the class path of your application. It's only meant to be use on ES nodes.

**Comment by eddygithub** [comment]
@bleskes You are right.  I am starting Transport client fro my application.  This is what I have done.  It start server nodes and client from my application.  

When I start the server node, I changed the path.home to where I have elasticsearch installed with Marvel in the plugins folder because I want to see the server node on Marvel.  "I don't have Marvel on the classpath".  Is it possible to start server node from my application which Marvel detects and shows on its dashboard?

**Comment by bleskes** [comment]
@eddygithub double checking I understand - the node you starts are in process (via NodeBuilder) or out of your application in a different process?

**Comment by eddygithub** [comment]
@bleskes I start the node via NodeBuilder

like nodeBuilder().settings(settings).node();

**Comment by eddygithub** [comment]
@bleskes my company is considering using elasticsearch as our cached data search engine.  I am trying to build some tools to provide an easier way to form es cluster and monitor the cluster to minimize the learning curve for our developer

**Comment by eddygithub** [comment]
@bleskes I changed my method to execute command line instead of using NodeBuilder.
Everything works fine!  It still annoys why there isn't an alternate in Java api equivalent of the "elasticsearch" command line

**Comment by bleskes** [comment]
@eddygithub these two methods do two different things. Using the node builder starts an ES within the same process. using the command line spawns a new process (which is probably better for you, if I understand correctly what your are doing). If you really want to use the NodeBuilder, try settings `path.plugins` to a non existing path (or one without marvel) when starting your transport client
