### ISSUE TITLE
Kibana 4 with elastic search 1.4.4 gives connect econnrefused

### ISSUE THREAD

**Issue by ranasingh** [elasticsearch/elasticsearch#9872]
Hi,

I'm trying out kibana 4.0.0 and have downloaded it and elasticsearch 1.4.4, but get an error when kibana tries to connect to elasticsearch.

My setup:
OS: Windows 7

I have posted the same question here: https://groups.google.com/forum/?nomobile=true#!topic/elasticsearch/TsOQ6e_fGx4

The only changes I have done is in kibana.yml where I have set host: "0:0:0:0:0:0:0:0", as I saw that elasticsearch is listening on an ipv6 address and so changed it in kibana to do the same. Otherwise no changes in any of the config files. 
Both services start up nicely, and http://localhost:9200 gives this output:
{
  "status" : 200,
  "name" : "Argus",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "1.4.4",
    "build_hash" : "c88f77ffc81301dfa9dfd81ca2232f09588bd512",
    "build_timestamp" : "2015-02-19T13:05:36Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.3"
  },
  "tagline" : "You Know, for Search"
}

Elastic-search console window on startup:
[2015-02-25 10:58:42,339][WARN ][bootstrap                ] jvm uses the client vm, make sure to run `java` with the server vm for best performance by adding `-server` to the command line
[2015-02-25 10:58:42,408][INFO ][node                     ] [Argus] version[1.4.4], pid[8640], build[c88f77f/2015-02-19T13:05:36Z]
[2015-02-25 10:58:42,408][INFO ][node                     ] [Argus] initializing ...
[2015-02-25 10:58:42,412][INFO ][plugins                  ] [Argus] loaded [], sites []
[2015-02-25 10:58:45,563][INFO ][node                     ] [Argus] initialized
[2015-02-25 10:58:45,563][INFO ][node                     ] [Argus] starting ...
[2015-02-25 10:58:45,899][INFO ][transport                ] [Argus] bound_address {inet[/0:0:0:0:0:0:0:0:9300]}, publish_address {inet[/139.113.102.160:9300]}
[2015-02-25 10:58:46,455][INFO ][discovery                ] [Argus] elasticsearch/LYg7WrfBSOeONOwbovB0IQ
[2015-02-25 10:58:50,227][INFO ][cluster.service          ] [Argus] new_master [Argus][LYg7WrfBSOeONOwbovB0IQ][NOLD0048][inet[/139.113.102.160:9300]], reason: zen-disco-join (elected_as_master
[2015-02-25 10:58:50,266][INFO ][gateway                  ] [Argus] recovered [0] indices into cluster_state
[2015-02-25 10:58:50,464][INFO ][http                     ] [Argus] bound_address {inet[/0:0:0:0:0:0:0:0:9200]}, publish_address {inet[/139.113.102.160:9200]}
[2015-02-25 10:58:50,465][INFO ][node                     ] [Argus] started

Kibana console window on startup:
{"@timestamp":"2015-02-25T09:58:56.064Z","level":"info","message":"Listening on :::5601","node_env":"\"production\""}

But when I go to http://localhost:5601, it tries to load the webpage but crashes with an error message:
 Fatal Error
Kibana: Unable to connect to Elasticsearch
Error: unknown error
    at respond (http://localhost:5601/index.js?_b=5888:81675:15)
    at checkRespForFailure (http://localhost:5601/index.js?_b=5888:81641:7)
    at http://localhost:5601/index.js?_b=5888:80304:7
    at wrappedErrback (http://localhost:5601/index.js?_b=5888:20897:78)
    at wrappedErrback (http://localhost:5601/index.js?_b=5888:20897:78)
    at wrappedErrback (http://localhost:5601/index.js?_b=5888:20897:78)
    at http://localhost:5601/index.js?_b=5888:21030:76
    at Scope.$eval (http://localhost:5601/index.js?_b=5888:22017:28)
    at Scope.$digest (http://localhost:5601/index.js?_b=5888:21829:31)
    at Scope.$apply (http://localhost:5601/index.js?_b=5888:22121:24)

Kibana console spits out this message (Note the connect econnrefused-error message):
{"@timestamp":"2015-02-25T09:59:03.589Z","level":"info","message":"GET / 304 - 6ms","node_env":"\"production\"","request":{"method":"GET","url":"/","headers":{"host":"localhost:5601","connection":"kee
{"@timestamp":"2015-02-25T09:59:03.700Z","level":"info","message":"GET /styles/main.css?_b=5888 304 - 4ms","node_env":"\"production\"","request":{"method":"GET","url":"/styles/main.css?_b=5888","heade
{"@timestamp":"2015-02-25T09:59:03.701Z","level":"info","message":"GET /images/initial_load.gif 304 - 5ms","node_env":"\"production\"","request":{"method":"GET","url":"/images/initial_load.gif","heade
{"@timestamp":"2015-02-25T09:59:03.702Z","level":"info","message":"GET /bower_components/requirejs/require.js?_b=5888 304 - 5ms","node_env":"\"production\"","request":{"method":"GET","url":"/bower_com
{"@timestamp":"2015-02-25T09:59:03.703Z","level":"info","message":"GET /require.config.js?_b=5888 304 - 5ms","node_env":"\"production\"","request":{"method":"GET","url":"/require.config.js?_b=5888","h
{"@timestamp":"2015-02-25T09:59:03.797Z","level":"info","message":"GET /index.js?_b=5888 304 - 1ms","node_env":"\"production\"","request":{"method":"GET","url":"/index.js?_b=5888","headers":{"host":"l
{"@timestamp":"2015-02-25T09:59:03.801Z","level":"info","message":"GET /styles/theme/elk.ico 304 - 1ms","node_env":"\"production\"","request":{"method":"GET","url":"/styles/theme/elk.ico","headers":{"
{"@timestamp":"2015-02-25T09:59:04.200Z","level":"info","message":"GET /config?_b=5888 304 - 3ms","node_env":"\"production\"","request":{"method":"GET","url":"/config?_b=5888","headers":{"host":"local
{"@timestamp":"2015-02-25T09:59:04.479Z","level":"info","message":"GET /images/no_border.png 304 - 2ms","node_env":"\"production\"","request":{"method":"GET","url":"/images/no_border.png","headers":{"
{"@timestamp":"2015-02-25T09:59:05.491Z","level":"error","message":"connect ECONNREFUSED","node_env":"\"production\"","error":{"message":"connect ECONNREFUSED","name":"Error","stack":"Error: connect E
{"@timestamp":"2015-02-25T09:59:05.493Z","level":"info","message":"GET / 502 - 1007ms","node_env":"\"production\"","request":{"method":"GET","url":"/elasticsearch/","headers":{"host":"localhost:5601",
{"@timestamp":"2015-02-25T09:59:05.510Z","level":"info","message":"GET /bower_components/font-awesome/fonts/fontawesome-webfont.woff?v=4.2.0 304 - 5ms","node_env":"\"production\"","request":{"method":

When I close the kibana.bat - window, I get this from the elasticsearch.bat-window:
java.io.IOException: An existing connection was forcibly closed by the remote host
        at sun.nio.ch.SocketDispatcher.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:192)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379)
        at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:64)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

So from the error message it looks like kibana has been able to contact elastic search, but why it fails beats me. Googling for "connect econnrefused" gives me that the service being looked for is not there, in my case it will mean that kibana can't find elastic search. But then why the error message in elastic search console window?

I'm out of ideas. Any help on this matter would be much appreciated!

**Comment by clintongormley** [comment]
@rashidkpc is this something you've seen before?

You may have more luck opening this ticket on the kibana issues list.
