### ISSUE TITLE
investigate strange reflection hack found by percolation tests.

### ISSUE THREAD

**Issue by rmuir** [elasticsearch/elasticsearch#9882]
Maybe i unfairly blamed percolator, but at least its tests found this (in tests.policy)

// needed by percolation??? (what is going on here)
+ permission java.lang.RuntimePermission "accessClassInPackage.sun.reflect";

**Comment by rmuir** [comment]
I investigated, its something coming out of the groovy engine. I'll fix the comment in the test policy,

   > Caused by: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "accessClassInPackage.sun.reflect")
   >    at java.security.AccessControlContext.checkPermission(AccessControlContext.java:457)
   >    at java.security.AccessController.checkPermission(AccessController.java:884)
   >    at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
   >    at java.lang.SecurityManager.checkPackageAccess(SecurityManager.java:1564)
   >    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:311)
   >    at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
   >    at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:676)
