### ISSUE TITLE
lucene410 not in class path

### ISSUE THREAD

**Issue by podopie** [elasticsearch/elasticsearch#9929]
Running elasticsearch 1.3.4 (required), java 1.7.0_75 (under jenv)

error
```sh
Caused by: java.lang.IllegalArgumentException: A SPI class of type org.apache.lucene.codecs.Codec with name 'Lucene410' does not exist. You need to add the corresponding JAR file supporting this SPI to your classpath.The current classpath supports the following names: [SimpleText, Appending, Lucene40, Lucene3x, Lucene41, Lucene42, Lucene45, Lucene46, Lucene49]
	at org.apache.lucene.util.NamedSPILoader.lookup(NamedSPILoader.java:109)
	at org.apache.lucene.codecs.Codec.forName(Codec.java:95)
	at org.apache.lucene.index.SegmentInfos.read(SegmentInfos.java:359)
	at org.apache.lucene.index.SegmentInfos$1.doBody(SegmentInfos.java:457)
	at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:912)
	at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:758)
	at org.apache.lucene.index.SegmentInfos.read(SegmentInfos.java:453)
	at org.elasticsearch.common.lucene.Lucene.readSegmentInfos(Lucene.java:98)
	at org.elasticsearch.index.gateway.local.LocalIndexShardGateway.recover(LocalIndexShardGateway.java:122)
```

I believe this has something to do with the java setup on my machine, but nonetheless, I'm unable to start the cluster. Is this a bug or do I have some cleanup to do on my machine?

**Comment by dadoonet** [comment]
Elasticsearch 1.3.4 uses         

    <lucene.version>4.9.1</lucene.version>

You are probably mixing things

**Comment by podopie** [comment]
All I've done is use brew to install the specific elasticsearch version; I imagine when uninstalling a previous version of elasticsearch (latest), the brew uninstall likely did not clean up completely?

**Comment by podopie** [comment]
personal note, will close:
brew uninstall doesn't delete data/logs/plugins folders, so I deleted those specifically to clean up the install, and everything seems to now be working. Appreciate the callout, @dadoonet
